/* eslint-disable no-console */
import { Difficulty, ExerciseType } from '@prisma/client';

// ============================================================================
// SECTION 1: FOUNDATION (Levels 1-20)
// ============================================================================

const section1Lessons = [
  // HOME ROW MASTERY (Lessons 1-5)
  {
    level: 1,
    order: 1,
    section: 1,
    title: 'Home Row - Individual Keys',
    description: 'Learn each home row key with delays between presses',
    keys: ['a', 's', 'd', 'f', 'j', 'k', 'l', ';'],
    difficulty: Difficulty.BEGINNER,
    targetWpm: 15,
    minAccuracy: 90,
    exerciseType: ExerciseType.KEYS,
    targetFingers: [
      'pinky-left',
      'ring-left',
      'middle-left',
      'index-left',
      'index-right',
      'middle-right',
      'ring-right',
      'pinky-right',
    ],
    unlockAfter: [],
    content: 'a a a s s s d d d f f f j j j k k k l l l ; ; ;',
  },
  {
    level: 2,
    order: 2,
    section: 1,
    title: 'Home Row - Two-Key Combinations',
    description: 'Practice common two-key patterns on the home row',
    keys: ['a', 's', 'd', 'f', 'j', 'k', 'l', ';'],
    difficulty: Difficulty.BEGINNER,
    targetWpm: 18,
    minAccuracy: 92,
    exerciseType: ExerciseType.KEYS,
    targetFingers: [
      'pinky-left',
      'ring-left',
      'middle-left',
      'index-left',
      'index-right',
      'middle-right',
      'ring-right',
      'pinky-right',
    ],
    unlockAfter: [],
    content: 'as df jk kl as df jk kl sa fd kj lk sa fd kj lk',
  },
  {
    level: 3,
    order: 3,
    section: 1,
    title: 'Home Row - Three-Key Patterns',
    description: 'Build fluency with three-key combinations',
    keys: ['a', 's', 'd', 'f', 'j', 'k', 'l', ';'],
    difficulty: Difficulty.BEGINNER,
    targetWpm: 20,
    minAccuracy: 93,
    exerciseType: ExerciseType.KEYS,
    targetFingers: [
      'pinky-left',
      'ring-left',
      'middle-left',
      'index-left',
      'index-right',
      'middle-right',
      'ring-right',
      'pinky-right',
    ],
    unlockAfter: [],
    content: 'asd fds jkl kl; sad dsf lkj ;lk asd fds jkl kl;',
  },
  {
    level: 4,
    order: 4,
    section: 1,
    title: 'Home Row - Full Flow',
    description: 'Type smoothly across the entire home row',
    keys: ['a', 's', 'd', 'f', 'j', 'k', 'l', ';'],
    difficulty: Difficulty.BEGINNER,
    targetWpm: 22,
    minAccuracy: 94,
    exerciseType: ExerciseType.KEYS,
    targetFingers: [
      'pinky-left',
      'ring-left',
      'middle-left',
      'index-left',
      'index-right',
      'middle-right',
      'ring-right',
      'pinky-right',
    ],
    unlockAfter: [],
    content: 'asdf jkl; fdsa ;lkj asdf jkl; fdsa ;lkj asdfg hjkl;',
  },
  {
    level: 5,
    order: 5,
    section: 1,
    title: 'Home Row Checkpoint',
    description: 'Master the home row with this checkpoint test',
    keys: ['a', 's', 'd', 'f', 'j', 'k', 'l', ';'],
    difficulty: Difficulty.BEGINNER,
    targetWpm: 25,
    minAccuracy: 95,
    exerciseType: ExerciseType.WORDS,
    targetFingers: [],
    unlockAfter: [],
    isCheckpoint: true,
    content: 'sad lad fall lass jass flaskask dad jak lads salad fallssal ask',
  },

  // INDEX FINGER EXTENSION (Lessons 6-10)
  {
    level: 6,
    order: 6,
    section: 1,
    title: 'Index Fingers - G and H',
    description: 'Extend your index fingers to reach G and H',
    keys: ['g', 'h', 'f', 'j'],
    difficulty: Difficulty.BEGINNER,
    targetWpm: 20,
    minAccuracy: 92,
    exerciseType: ExerciseType.KEYS,
    targetFingers: ['index-left', 'index-right'],
    unlockAfter: [],
    content: 'gf hj fg jh gf hj fg jh gg hh ff jj gh hg gh hg',
  },
  {
    level: 7,
    order: 7,
    section: 1,
    title: 'Index Fingers - B and N',
    description: 'Add B and N to your index finger repertoire',
    keys: ['b', 'n', 'f', 'j'],
    difficulty: Difficulty.BEGINNER,
    targetWpm: 20,
    minAccuracy: 92,
    exerciseType: ExerciseType.KEYS,
    targetFingers: ['index-left', 'index-right'],
    unlockAfter: [],
    content: 'bf nj fb jn bf nj fb jn bb nn ff jj bn nb bn nb',
  },
  {
    level: 8,
    order: 8,
    section: 1,
    title: 'Index Fingers - Combined Practice',
    description: 'Practice all index finger keys together',
    keys: ['g', 'h', 'b', 'n', 'f', 'j'],
    difficulty: Difficulty.BEGINNER,
    targetWpm: 22,
    minAccuracy: 93,
    exerciseType: ExerciseType.KEYS,
    targetFingers: ['index-left', 'index-right'],
    unlockAfter: [],
    content: 'gh bn fj hg nb jf ghbn fjgh bnhg fjgh ghbn fjgh',
  },
  {
    level: 9,
    order: 9,
    section: 1,
    title: 'Index Fingers - Word Practice',
    description: 'Type real words using your new keys',
    keys: ['g', 'h', 'b', 'n'],
    difficulty: Difficulty.BEGINNER,
    targetWpm: 24,
    minAccuracy: 94,
    exerciseType: ExerciseType.WORDS,
    targetFingers: ['index-left', 'index-right'],
    unlockAfter: [],
    content: 'grab hung band nag bash hang gab jab fan gash ban hang',
  },
  {
    level: 10,
    order: 10,
    section: 1,
    title: 'Index Finger Checkpoint',
    description: 'Checkpoint for home row plus index finger extensions',
    keys: [],
    difficulty: Difficulty.BEGINNER,
    targetWpm: 27,
    minAccuracy: 95,
    exerciseType: ExerciseType.WORDS,
    targetFingers: [],
    unlockAfter: [],
    isCheckpoint: true,
    content: 'hang bang gash flash dash bash gang land hand sand bland',
  },

  // TOP ROW INTRODUCTION (Lessons 11-15)
  {
    level: 11,
    order: 11,
    section: 1,
    title: 'Top Row - Left Hand (QWERT)',
    description: 'Learn the top row keys for your left hand',
    keys: ['q', 'w', 'e', 'r', 't'],
    difficulty: Difficulty.BEGINNER,
    targetWpm: 20,
    minAccuracy: 90,
    exerciseType: ExerciseType.KEYS,
    targetFingers: ['pinky-left', 'ring-left', 'middle-left', 'index-left'],
    unlockAfter: [],
    content: 'qw er rt we rt qw er rt qwert trewq qwert trewq',
  },
  {
    level: 12,
    order: 12,
    section: 1,
    title: 'Top Row - Right Hand (YUIOP)',
    description: 'Learn the top row keys for your right hand',
    keys: ['y', 'u', 'i', 'o', 'p'],
    difficulty: Difficulty.BEGINNER,
    targetWpm: 20,
    minAccuracy: 90,
    exerciseType: ExerciseType.KEYS,
    targetFingers: ['index-right', 'middle-right', 'ring-right', 'pinky-right'],
    unlockAfter: [],
    content: 'yu io op ui oi yu io yuiop poiuy yuiop poiuy',
  },
  {
    level: 13,
    order: 13,
    section: 1,
    title: 'Top Row - Combined Practice',
    description: 'Practice both hands on the top row',
    keys: ['q', 'w', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p'],
    difficulty: Difficulty.BEGINNER,
    targetWpm: 22,
    minAccuracy: 92,
    exerciseType: ExerciseType.KEYS,
    targetFingers: [],
    unlockAfter: [],
    content: 'qwerty uiop ytrewq poiuy qwerty uiop ytrewq poiuy',
  },
  {
    level: 14,
    order: 14,
    section: 1,
    title: 'Top Row - Common Digraphs',
    description: 'Practice common two-letter combinations: qu, er, ty, ui, op',
    keys: ['q', 'u', 'e', 'r', 't', 'y', 'u', 'i', 'o', 'p'],
    difficulty: Difficulty.BEGINNER,
    targetWpm: 24,
    minAccuracy: 93,
    exerciseType: ExerciseType.WORDS,
    targetFingers: [],
    unlockAfter: [],
    content: 'qu er ty ui op que try tip top per quit type ripe upper',
  },
  {
    level: 15,
    order: 15,
    section: 1,
    title: 'Top Row Checkpoint',
    description: 'Checkpoint test for top row mastery',
    keys: [],
    difficulty: Difficulty.BEGINNER,
    targetWpm: 28,
    minAccuracy: 94,
    exerciseType: ExerciseType.WORDS,
    targetFingers: [],
    unlockAfter: [],
    isCheckpoint: true,
    content: 'query tower power upper peter quiet river write outer trade',
  },

  // BOTTOM ROW INTRODUCTION (Lessons 16-20)
  {
    level: 16,
    order: 16,
    section: 1,
    title: 'Bottom Row - Left Hand (ZXCV)',
    description: 'Learn the bottom row keys for your left hand',
    keys: ['z', 'x', 'c', 'v'],
    difficulty: Difficulty.BEGINNER,
    targetWpm: 18,
    minAccuracy: 90,
    exerciseType: ExerciseType.KEYS,
    targetFingers: ['pinky-left', 'ring-left', 'middle-left', 'index-left'],
    unlockAfter: [],
    content: 'zx xc cv zx xc cv zxcv vcxz zxcv vcxz',
  },
  {
    level: 17,
    order: 17,
    section: 1,
    title: 'Bottom Row - Right Hand (BNM)',
    description: 'Learn the bottom row keys for your right hand',
    keys: ['b', 'n', 'm'],
    difficulty: Difficulty.BEGINNER,
    targetWpm: 18,
    minAccuracy: 90,
    exerciseType: ExerciseType.KEYS,
    targetFingers: ['index-right', 'middle-right', 'ring-right'],
    unlockAfter: [],
    content: 'bn nm mb bnm mnb bnm mnb',
  },
  {
    level: 18,
    order: 18,
    section: 1,
    title: 'Bottom Row - Combined Practice',
    description: 'Practice all bottom row keys together',
    keys: ['z', 'x', 'c', 'v', 'b', 'n', 'm'],
    difficulty: Difficulty.BEGINNER,
    targetWpm: 20,
    minAccuracy: 92,
    exerciseType: ExerciseType.KEYS,
    targetFingers: [],
    unlockAfter: [],
    content: 'zxcv bnm vcxz mnb zxcv bnm vcxz mnb',
  },
  {
    level: 19,
    order: 19,
    section: 1,
    title: 'Bottom Row - Word Practice',
    description: 'Type real words using bottom row keys',
    keys: [],
    difficulty: Difficulty.BEGINNER,
    targetWpm: 22,
    minAccuracy: 93,
    exerciseType: ExerciseType.WORDS,
    targetFingers: [],
    unlockAfter: [],
    content: 'zone come move vibe numb maze cave beam cave maze',
  },
  {
    level: 20,
    order: 20,
    section: 1,
    title: 'Section 1 Checkpoint - Full Alphabet',
    description: 'Master all letter keys with this comprehensive checkpoint',
    keys: [],
    difficulty: Difficulty.BEGINNER,
    targetWpm: 30,
    minAccuracy: 95,
    exerciseType: ExerciseType.SENTENCES,
    targetFingers: [],
    unlockAfter: [],
    isCheckpoint: true,
    content:
      'the quick brown fox jumps over the lazy dog near the riverbank while making very complex movements',
  },
];

// ============================================================================
// SECTION 2: SKILL BUILDING (Levels 21-40)
// ============================================================================

const section2Lessons = [
  // COMMON DIGRAPHS (Lessons 21-25)
  {
    level: 21,
    order: 21,
    section: 2,
    title: 'Digraphs - TH',
    description: 'Master the most common digraph in English',
    keys: ['t', 'h'],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 30,
    minAccuracy: 94,
    exerciseType: ExerciseType.WORDS,
    targetFingers: ['index-left', 'index-right'],
    unlockAfter: [],
    content: 'the that this them then than with through think thank weather',
  },
  {
    level: 22,
    order: 22,
    section: 2,
    title: 'Digraphs - CH and SH',
    description: 'Practice ch and sh combinations',
    keys: ['c', 'h', 's', 'h'],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 30,
    minAccuracy: 94,
    exerciseType: ExerciseType.WORDS,
    targetFingers: [],
    unlockAfter: [],
    content: 'child choose chair teacher church should shell fish shallow shape',
  },
  {
    level: 23,
    order: 23,
    section: 2,
    title: 'Digraphs - WH and PH',
    description: 'Practice wh and ph combinations',
    keys: ['w', 'h', 'p', 'h'],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 30,
    minAccuracy: 94,
    exerciseType: ExerciseType.WORDS,
    targetFingers: [],
    unlockAfter: [],
    content: 'what when where which white phone photo graph elephant phrase',
  },
  {
    level: 24,
    order: 24,
    section: 2,
    title: 'Digraphs - Common Vowel Pairs',
    description: 'Practice ea, ou, ai, ee combinations',
    keys: [],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 32,
    minAccuracy: 94,
    exerciseType: ExerciseType.WORDS,
    targetFingers: [],
    unlockAfter: [],
    content: 'each read team about sound main rain free tree need great',
  },
  {
    level: 25,
    order: 25,
    section: 2,
    title: 'Digraph Checkpoint',
    description: 'Test your mastery of common letter combinations',
    keys: [],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 35,
    minAccuracy: 95,
    exerciseType: ExerciseType.SENTENCES,
    targetFingers: [],
    unlockAfter: [],
    isCheckpoint: true,
    content:
      'the weather should change when the teacher chooses which phrase to read about the white elephant',
  },

  // COMMON TRIGRAMS (Lessons 26-30)
  {
    level: 26,
    order: 26,
    section: 2,
    title: 'Trigrams - THE',
    description: 'Master typing the most common word in English',
    keys: ['t', 'h', 'e'],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 32,
    minAccuracy: 95,
    exerciseType: ExerciseType.WORDS,
    targetFingers: [],
    unlockAfter: [],
    content: 'the the the the then them there these their other mother father',
  },
  {
    level: 27,
    order: 27,
    section: 2,
    title: 'Trigrams - AND and ING',
    description: 'Practice and and ing patterns',
    keys: [],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 32,
    minAccuracy: 95,
    exerciseType: ExerciseType.WORDS,
    targetFingers: [],
    unlockAfter: [],
    content: 'and band hand land going making taking walking talking running',
  },
  {
    level: 28,
    order: 28,
    section: 2,
    title: 'Trigrams - ION and TION',
    description: 'Practice ion and tion endings',
    keys: [],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 33,
    minAccuracy: 95,
    exerciseType: ExerciseType.WORDS,
    targetFingers: [],
    unlockAfter: [],
    content: 'action nation station question position information education attention',
  },
  {
    level: 29,
    order: 29,
    section: 2,
    title: 'Trigrams - Common Prefixes',
    description: 'Practice common word beginnings',
    keys: [],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 33,
    minAccuracy: 95,
    exerciseType: ExerciseType.WORDS,
    targetFingers: [],
    unlockAfter: [],
    content: 'pre con dis under over before after across around between through',
  },
  {
    level: 30,
    order: 30,
    section: 2,
    title: 'Trigram Checkpoint',
    description: 'Comprehensive test of common word patterns',
    keys: [],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 36,
    minAccuracy: 95,
    exerciseType: ExerciseType.SENTENCES,
    targetFingers: [],
    unlockAfter: [],
    isCheckpoint: true,
    content:
      'the information and education station provides attention to the question about the action taking place across the nation',
  },

  // ALTERNATING HANDS (Lessons 31-35)
  {
    level: 31,
    order: 31,
    section: 2,
    title: 'Alternating Hands - Easy Words',
    description: 'Type words that naturally alternate between hands',
    keys: [],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 35,
    minAccuracy: 95,
    exerciseType: ExerciseType.WORDS,
    targetFingers: [],
    unlockAfter: [],
    content: 'island theory penalty authentic giant formal turkey problem authentic',
  },
  {
    level: 32,
    order: 32,
    section: 2,
    title: 'Alternating Hands - Medium Words',
    description: 'Practice longer alternating hand words',
    keys: [],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 36,
    minAccuracy: 95,
    exerciseType: ExerciseType.WORDS,
    targetFingers: [],
    unlockAfter: [],
    content: 'neighbor element suspend downtown ancient visible chairman visual',
  },
  {
    level: 33,
    order: 33,
    section: 2,
    title: 'Alternating Hands - Advanced',
    description: 'Type complex alternating hand words',
    keys: [],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 37,
    minAccuracy: 96,
    exerciseType: ExerciseType.WORDS,
    targetFingers: [],
    unlockAfter: [],
    content: 'auditory authentic dismantle endowment firmament indigenous ivory',
  },
  {
    level: 34,
    order: 34,
    section: 2,
    title: 'Alternating Hands - Sentences',
    description: 'Practice sentences with good hand alternation',
    keys: [],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 38,
    minAccuracy: 96,
    exerciseType: ExerciseType.SENTENCES,
    targetFingers: [],
    unlockAfter: [],
    content:
      'the giant turkey island provides an authentic visual element for the downtown chairman',
  },
  {
    level: 35,
    order: 35,
    section: 2,
    title: 'Alternating Hands Checkpoint',
    description: 'Checkpoint for alternating hand typing',
    keys: [],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 40,
    minAccuracy: 96,
    exerciseType: ExerciseType.SENTENCES,
    targetFingers: [],
    unlockAfter: [],
    isCheckpoint: true,
    content:
      'the authentic chairman provides visible elements for the downtown neighbor during the ancient penalty theory',
  },

  // SAME HAND WORDS (Lessons 36-39)
  {
    level: 36,
    order: 36,
    section: 2,
    title: 'Same Hand - Left Hand Words',
    description: 'Practice words typed entirely with the left hand',
    keys: [],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 32,
    minAccuracy: 94,
    exerciseType: ExerciseType.WORDS,
    targetFingers: ['pinky-left', 'ring-left', 'middle-left', 'index-left'],
    unlockAfter: [],
    content: 'was were best test rest vest text assert desert dress',
  },
  {
    level: 37,
    order: 37,
    section: 2,
    title: 'Same Hand - Right Hand Words',
    description: 'Practice words typed entirely with the right hand',
    keys: [],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 32,
    minAccuracy: 94,
    exerciseType: ExerciseType.WORDS,
    targetFingers: ['index-right', 'middle-right', 'ring-right', 'pinky-right'],
    unlockAfter: [],
    content: 'polo look upon hill jump milkonio pink link nylon',
  },
  {
    level: 38,
    order: 38,
    section: 2,
    title: 'Same Hand - Mixed Practice',
    description: 'Alternate between left and right hand words',
    keys: [],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 34,
    minAccuracy: 95,
    exerciseType: ExerciseType.WORDS,
    targetFingers: [],
    unlockAfter: [],
    content: 'polo vest look test pink rest milk best upon link',
  },
  {
    level: 39,
    order: 39,
    section: 2,
    title: 'Same Hand - Challenge',
    description: 'Type challenging same-hand sequences',
    keys: [],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 36,
    minAccuracy: 95,
    exerciseType: ExerciseType.SENTENCES,
    targetFingers: [],
    unlockAfter: [],
    content: 'we were at the crest of the hill to look upon the pink moon',
  },

  // SECTION 2 CHECKPOINT (Lesson 40)
  {
    level: 40,
    order: 40,
    section: 2,
    title: 'Section 2 Checkpoint - Skill Building',
    description: 'Comprehensive checkpoint for section 2 mastery',
    keys: [],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 45,
    minAccuracy: 96,
    exerciseType: ExerciseType.PARAGRAPHS,
    targetFingers: [],
    unlockAfter: [],
    isCheckpoint: true,
    content:
      'The quick brown fox jumps over the lazy dog while the authentic chairman provides information about the education station. The theory suggests that alternating hands creates better typing flow and reduces fatigue during extended practice sessions.',
  },
];

// ============================================================================
// SECTION 3: ADVANCED TECHNIQUES (Levels 41-60)
// ============================================================================

const section3Lessons = [
  // CAPITALIZATION (Lessons 41-44)
  {
    level: 41,
    order: 41,
    section: 3,
    title: 'Capitalization - Left Shift',
    description: 'Practice using left shift for right-hand capitals',
    keys: [],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 35,
    minAccuracy: 94,
    exerciseType: ExerciseType.WORDS,
    targetFingers: ['pinky-left'],
    unlockAfter: [],
    content: 'John Mary Peter Helen India Japan Mike Nancy Oliver Paula',
  },
  {
    level: 42,
    order: 42,
    section: 3,
    title: 'Capitalization - Right Shift',
    description: 'Practice using right shift for left-hand capitals',
    keys: [],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 35,
    minAccuracy: 94,
    exerciseType: ExerciseType.WORDS,
    targetFingers: ['pinky-right'],
    unlockAfter: [],
    content: 'Alice Bob Chris David Emma Frank George Sam Tom William',
  },
  {
    level: 43,
    order: 43,
    section: 3,
    title: 'Capitalization - Proper Nouns',
    description: 'Type sentences with proper nouns and capitals',
    keys: [],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 37,
    minAccuracy: 95,
    exerciseType: ExerciseType.SENTENCES,
    targetFingers: [],
    unlockAfter: [],
    content:
      'Mary and John visited Paris in France during August with their friend Peter from London.',
  },
  {
    level: 44,
    order: 44,
    section: 3,
    title: 'Capitalization Checkpoint',
    description: 'Master capitalization with this checkpoint',
    keys: [],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 40,
    minAccuracy: 96,
    exerciseType: ExerciseType.SENTENCES,
    targetFingers: [],
    unlockAfter: [],
    isCheckpoint: true,
    content:
      'The United States of America, Canada, Mexico, Brazil, and Argentina are countries in North and South America that Alice and Bob visited last summer.',
  },

  // NUMBER ROW (Lessons 45-52)
  {
    level: 45,
    order: 45,
    section: 3,
    title: 'Numbers - 1 and 2',
    description: 'Learn to type 1 and 2 on the number row',
    keys: ['1', '2'],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 28,
    minAccuracy: 92,
    exerciseType: ExerciseType.KEYS,
    targetFingers: ['pinky-left', 'ring-left'],
    unlockAfter: [],
    content: '1 2 1 2 12 21 12 21 112 221 121 212 1 2 1 2',
  },
  {
    level: 46,
    order: 46,
    section: 3,
    title: 'Numbers - 3 and 4',
    description: 'Learn to type 3 and 4 on the number row',
    keys: ['3', '4'],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 28,
    minAccuracy: 92,
    exerciseType: ExerciseType.KEYS,
    targetFingers: ['middle-left', 'index-left'],
    unlockAfter: [],
    content: '3 4 3 4 34 43 34 43 334 443 343 434 3 4 3 4',
  },
  {
    level: 47,
    order: 47,
    section: 3,
    title: 'Numbers - 5 and 6',
    description: 'Learn to type 5 and 6 on the number row',
    keys: ['5', '6'],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 28,
    minAccuracy: 92,
    exerciseType: ExerciseType.KEYS,
    targetFingers: ['index-left', 'index-right'],
    unlockAfter: [],
    content: '5 6 5 6 56 65 56 65 556 665 565 656 5 6 5 6',
  },
  {
    level: 48,
    order: 48,
    section: 3,
    title: 'Numbers - 7 and 8',
    description: 'Learn to type 7 and 8 on the number row',
    keys: ['7', '8'],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 28,
    minAccuracy: 92,
    exerciseType: ExerciseType.KEYS,
    targetFingers: ['index-right', 'middle-right'],
    unlockAfter: [],
    content: '7 8 7 8 78 87 78 87 778 887 787 878 7 8 7 8',
  },
  {
    level: 49,
    order: 49,
    section: 3,
    title: 'Numbers - 9 and 0',
    description: 'Learn to type 9 and 0 on the number row',
    keys: ['9', '0'],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 28,
    minAccuracy: 92,
    exerciseType: ExerciseType.KEYS,
    targetFingers: ['ring-right', 'pinky-right'],
    unlockAfter: [],
    content: '9 0 9 0 90 09 90 09 990 009 909 090 9 0 9 0',
  },
  {
    level: 50,
    order: 50,
    section: 3,
    title: 'Numbers - All Digits',
    description: 'Practice all number keys together',
    keys: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0'],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 30,
    minAccuracy: 93,
    exerciseType: ExerciseType.KEYS,
    targetFingers: [],
    unlockAfter: [],
    content: '1234567890 0987654321 1234567890 0987654321 1234567890',
  },
  {
    level: 51,
    order: 51,
    section: 3,
    title: 'Numbers - Practical Use',
    description: 'Type numbers in realistic contexts',
    keys: [],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 32,
    minAccuracy: 94,
    exerciseType: ExerciseType.SENTENCES,
    targetFingers: [],
    unlockAfter: [],
    content: 'Call me at 555-1234 or email john123@email.com before 9:00 on May 15 2024.',
  },
  {
    level: 52,
    order: 52,
    section: 3,
    title: 'Number Row Checkpoint',
    description: 'Master the number row with this checkpoint',
    keys: [],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 35,
    minAccuracy: 95,
    exerciseType: ExerciseType.SENTENCES,
    targetFingers: [],
    unlockAfter: [],
    isCheckpoint: true,
    content:
      'The meeting on January 15 2024 at 3:30 PM will include 127 participants from 45 countries with budget of $1,250,000.',
  },

  // BASIC PUNCTUATION (Lessons 53-56)
  {
    level: 53,
    order: 53,
    section: 3,
    title: 'Punctuation - Period and Comma',
    description: 'Practice periods and commas',
    keys: ['.', ','],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 35,
    minAccuracy: 94,
    exerciseType: ExerciseType.SENTENCES,
    targetFingers: ['ring-right', 'middle-right'],
    unlockAfter: [],
    content: 'Hello, world. Nice to meet you. How are you, friend? Good, thanks.',
  },
  {
    level: 54,
    order: 54,
    section: 3,
    title: 'Punctuation - Question and Exclamation',
    description: 'Practice question marks and exclamation points',
    keys: ['?', '!'],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 35,
    minAccuracy: 94,
    exerciseType: ExerciseType.SENTENCES,
    targetFingers: ['pinky-right'],
    unlockAfter: [],
    content: 'What time is it? Are you coming? Great news! How exciting! Really?',
  },
  {
    level: 55,
    order: 55,
    section: 3,
    title: 'Punctuation - Colon and Semicolon',
    description: 'Practice colons and semicolons',
    keys: [':', ';'],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 36,
    minAccuracy: 95,
    exerciseType: ExerciseType.SENTENCES,
    targetFingers: ['pinky-right'],
    unlockAfter: [],
    content: 'Note: please review; however, you may skip the intro: it is optional.',
  },
  {
    level: 56,
    order: 56,
    section: 3,
    title: 'Punctuation Checkpoint',
    description: 'Master basic punctuation with this checkpoint',
    keys: [],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 38,
    minAccuracy: 96,
    exerciseType: ExerciseType.SENTENCES,
    targetFingers: [],
    unlockAfter: [],
    isCheckpoint: true,
    content:
      'Hello, everyone! How are you doing today? Please note: the meeting starts at 9:00 AM; however, you may arrive early.',
  },

  // APOSTROPHES & QUOTES (Lessons 57-59)
  {
    level: 57,
    order: 57,
    section: 3,
    title: 'Apostrophes - Contractions',
    description: 'Practice typing contractions with apostrophes',
    keys: ["'"],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 36,
    minAccuracy: 95,
    exerciseType: ExerciseType.SENTENCES,
    targetFingers: ['pinky-right'],
    unlockAfter: [],
    content: "I'm don't can't won't shouldn't wouldn't couldn't it's that's what's",
  },
  {
    level: 58,
    order: 58,
    section: 3,
    title: 'Quotation Marks - Dialogue',
    description: 'Practice typing dialogue with quotation marks',
    keys: ['"'],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 37,
    minAccuracy: 95,
    exerciseType: ExerciseType.SENTENCES,
    targetFingers: ['pinky-right'],
    unlockAfter: [],
    content:
      'She said, "Hello there!" He replied, "How are you?" They answered, "We\'re doing great!"',
  },
  {
    level: 59,
    order: 59,
    section: 3,
    title: 'Quotes and Apostrophes Combined',
    description: 'Practice complex punctuation patterns',
    keys: ["'", '"'],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 38,
    minAccuracy: 96,
    exerciseType: ExerciseType.SENTENCES,
    targetFingers: [],
    unlockAfter: [],
    content:
      '"I can\'t believe it\'s already noon," she said. "Shouldn\'t we leave now?" he asked. "We\'re running late!"',
  },

  // SECTION 3 CHECKPOINT (Lesson 60)
  {
    level: 60,
    order: 60,
    section: 3,
    title: 'Section 3 Checkpoint - Advanced Techniques',
    description: 'Comprehensive checkpoint testing all advanced techniques',
    keys: [],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 55,
    minAccuracy: 97,
    exerciseType: ExerciseType.PARAGRAPHS,
    targetFingers: [],
    unlockAfter: [],
    isCheckpoint: true,
    content:
      'John said, "I can\'t believe we\'re meeting at 3:45 PM on January 15, 2024!" Mary replied, "That\'s wonderful! Should I call you at 555-1234?" They agreed: it was perfect timing; however, they wouldn\'t forget to confirm.',
  },
];

// Continue with sections 4, 5, and 6...
// Due to length constraints, I'll create a separate continuation file

export { section1Lessons, section2Lessons, section3Lessons };
