/* eslint-disable no-console */

// ============================================================================
// SECTION 1: FOUNDATION (Levels 1-25) — home row, accuracy, rhythm
// ============================================================================
const section1Contents = [
  'a s d f j k l ; a s d f j k l ; as df jk l; f j d k s l a ;',
  'fall sad flask lad ask fad jail ladle kafka salad fajitas all ask j',
  'q w e r t y u i o p we rt yu io op qu it wep query quiet',
  'quiet petit type quiet weep typer quiet poetry typewriter power query type',
  'asdf asdf asdf jkl; jkl; jkl; asdf jkl; asdf jkl;',
  'lkjh lkjh lkjh ;lkj ;lkj ;lkj ;lkjh ;lkjh',
  'qwer qwer qwer asdf asdf asdf zxcv zxcv zxcv',
  'pat pat pat pat pat pat pat pat pat pat',
  'jump jump jump jump jump jump jump jump jump jump',
  'drink drink drink drink drink drink drink drink drink drink',
  'flank flank flank flank flank flank flank flank flank flank',
  'glance glance glance glance glance glance glance glance glance glance',
  'brave brave brave brave brave brave brave brave brave brave',
  'craft craft craft craft craft craft craft craft craft craft',
  'drain drain drain drain drain drain drain drain drain drain',
  'flask flask flask flask flask flask flask flask flask flask',
  'grace grace grace grace grace grace grace grace grace grace',
  'harvest harvest harvest harvest harvest harvest harvest harvest harvest harvest',
  'journey journey journey journey journey journey journey journey journey journey',
  'kiln kiln kiln kiln kiln kiln kiln kiln kiln kiln',
  'lamp lamp lamp lamp lamp lamp lamp lamp lamp lamp',
  'machine machine machine machine machine machine machine machine machine machine',
  'nest nest nest nest nest nest nest nest nest nest',
  'ocean ocean ocean ocean ocean ocean ocean ocean ocean ocean',
];

// ============================================================================
// SECTION 2: SKILL BUILDING (Levels 26-50) — words, punctuation, rhythm
// ============================================================================
const section2Contents = [
  'fall sad flask lad ask fad jail ladle kafka salad fajitas all ask j',
  'asdf asdf asdf jkl; jkl; jkl; asdf jkl; asdf jkl;',
  'lkjh lkjh lkjh ;lkj ;lkj ;lkj ;lkjh ;lkjh',
  'qwer qwer qwer asdf asdf asdf zxcv zxcv zxcv',
  'pat pat pat pat pat pat pat pat pat pat',
  'jump jump jump jump jump jump jump jump jump jump',
  'drink drink drink drink drink drink drink drink drink drink',
  'flank flank flank flank flank flank flank flank flank flank',
  'glance glance glance glance glance glance glance glance glance glance',
  'brave brave brave brave brave brave brave brave brave brave',
  'craft craft craft craft craft craft craft craft craft craft',
  'drain drain drain drain drain drain drain drain drain drain',
  'flask flask flask flask flask flask flask flask flask flask',
  'grace grace grace grace grace grace grace grace grace grace',
  'harvest harvest harvest harvest harvest harvest harvest harvest harvest harvest',
  'journey journey journey journey journey journey journey journey journey journey',
  'kiln kiln kiln kiln kiln kiln kiln kiln kiln kiln',
  'lamp lamp lamp lamp lamp lamp lamp lamp lamp lamp',
  'machine machine machine machine machine machine machine machine machine machine',
  'nest nest nest nest nest nest nest nest nest nest',
  'ocean ocean ocean ocean ocean ocean ocean ocean ocean ocean',
  'quartz quartz quartz quartz quartz quartz quartz quartz quartz quartz',
  'rust rust rust rust rust rust rust rust rust rust',
  'salt salt salt salt salt salt salt salt salt salt',
  'tent tent tent tent tent tent tent tent tent tent',
  'ultra ultra ultra ultra ultra ultra ultra ultra ultra ultra',
  'vessel vessel vessel vessel vessel vessel vessel vessel vessel vessel',
  'whale whale whale whale whale whale whale whale whale whale',
  'xenon xenon xenon xenon xenon xenon xenon xenon xenon xenon',
  'yield yield yield yield yield yield yield yield yield yield',
  'zest zest zest zest zest zest zest zest zest zest',
  'the quick brown fox jumps over the lazy dog',
  'pack my box with five dozen liquor jugs',
  'how vexingly quick daft zebras jump',
  'bright vixens jump; dozy fowl quack',
  'sphinx of black quartz, judge my vow',
];

// ============================================================================
// SECTION 3: ADVANCED TECHNIQUES (Levels 51-75) — speed, rhythm, mastery
// ============================================================================
const section3Contents = [
  'q w e r t y u i o p we rt yu io op qu it wep query quiet',
  'asdf asdf asdf jkl; jkl; jkl; asdf jkl; asdf jkl;',
  'lkjh lkjh lkjh ;lkj ;lkj ;lkj ;lkjh ;lkjh',
  'qwer qwer qwer asdf asdf asdf zxcv zxcv zxcv',
  'pat pat pat pat pat pat pat pat pat pat',
  'jump jump jump jump jump jump jump jump jump jump',
  'drink drink drink drink drink drink drink drink drink drink',
  'flank flank flank flank flank flank flank flank flank flank',
  'glance glance glance glance glance glance glance glance glance glance',
  'brave brave brave brave brave brave brave brave brave brave',
  'craft craft craft craft craft craft craft craft craft craft',
  'drain drain drain drain drain drain drain drain drain drain',
  'flask flask flask flask flask flask flask flask flask flask',
  'grace grace grace grace grace grace grace grace grace grace',
  'harvest harvest harvest harvest harvest harvest harvest harvest harvest harvest',
  'journey journey journey journey journey journey journey journey journey journey',
  'kiln kiln kiln kiln kiln kiln kiln kiln kiln kiln',
  'lamp lamp lamp lamp lamp lamp lamp lamp lamp lamp',
  'machine machine machine machine machine machine machine machine machine machine',
  'nest nest nest nest nest nest nest nest nest nest',
  'ocean ocean ocean ocean ocean ocean ocean ocean ocean ocean',
  'quartz quartz quartz quartz quartz quartz quartz quartz quartz quartz',
  'rust rust rust rust rust rust rust rust rust rust',
  'salt salt salt salt salt salt salt salt salt salt',
  'tent tent tent tent tent tent tent tent tent tent',
  'ultra ultra ultra ultra ultra ultra ultra ultra ultra ultra',
  'vessel vessel vessel vessel vessel vessel vessel vessel vessel vessel',
  'whale whale whale whale whale whale whale whale whale whale',
  'xenon xenon xenon xenon xenon xenon xenon xenon xenon xenon',
  'yield yield yield yield yield yield yield yield yield yield',
  'zest zest zest zest zest zest zest zest zest zest',
  'the quick brown fox jumps over the lazy dog',
  'pack my box with five dozen liquor jugs',
  'how vexingly quick daft zebras jump',
  'bright vixens jump; dozy fowl quack',
  'sphinx of black quartz, judge my vow',
  'lorem ipsum dolor sit amet, consectetur adipiscing elit',
  'sed do eiusmod tempor incididunt ut labore et dolore magna aliqua',
  'ut enim ad minim veniam, quis nostrud exercitation ullamco laboris',
  'duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore',
  'excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum',
];

// Export raw arrays for use in seed.ts with makeLessons
export { section1Contents, section2Contents, section3Contents };