/* eslint-disable no-console */
import { Difficulty, ExerciseType } from '@prisma/client';
import { deriveKeys } from './seed-utils';

// ============================================================================
// SECTION 1: FOUNDATION (Levels 1-12) — home row, accuracy, rhythm
// ============================================================================

const section1Raw = [
  {
    level: 1, order: 1, section: 1,
    title: 'Home Row Warmup',
    description: 'Meet the home row keys and build finger memory.',
    difficulty: Difficulty.BEGINNER, targetWpm: 15, minAccuracy: 90,
    exerciseType: ExerciseType.KEYS,
    targetFingers: ['pinky-left', 'ring-left', 'middle-left', 'index-left', 'index-right', 'middle-right', 'ring-right', 'pinky-right'],
    unlockAfter: [],
    content: 'a s d f j k l ; a s d f j k l ; as df jk l; f j d k s l a ;',
  },
  {
    level: 2, order: 2, section: 1,
    title: 'Home Row Words',
    description: 'Short words built only from home row keys.',
    difficulty: Difficulty.BEGINNER, targetWpm: 18, minAccuracy: 92,
    exerciseType: ExerciseType.WORDS,
    targetFingers: ['pinky-left', 'ring-left', 'middle-left', 'index-left', 'index-right', 'middle-right', 'ring-right', 'pinky-right'],
    unlockAfter: [],
    content: 'fall sad flask lad ask fad jail ladle kafka salad fajitas all ask j',
  },
  {
    level: 3, order: 3, section: 1,
    title: 'Top Row Intro',
    description: 'Add the top row: q w e r t y u i o p.',
    difficulty: Difficulty.BEGINNER, targetWpm: 18, minAccuracy: 90,
    exerciseType: ExerciseType.KEYS,
    targetFingers: ['pinky-left', 'ring-left', 'middle-left', 'index-left', 'index-right', 'middle-right', 'ring-right', 'pinky-right'],
    unlockAfter: [],
    content: 'q w e r t y u i o p we rt yu io op qu it wep query quiet低温',
  },
  {
    level: 4, order: 4, section: 1,
    title: 'Top Row Words',
    description: 'Common words using the top row.',
    difficulty: Difficulty.BEGINNER, targetWpm: 20, minAccuracy: 92,
    exerciseType: ExerciseType.WORDS,
    targetFingers: [],
    unlockAfter: [],
    content: 'quiet petit type quiet weep typer quiet poetry typewriter power query type',
  },
  {
    level: 5, order: 5, section: 1,
    title: 'Bottom Row Intro',
    description: 'Add the bottom row: z x c v b n m , . /',
    difficulty: Difficulty.BEGINNER, targetWpm: 18, minAccuracy: 90,
    exerciseType: ExerciseType.KEYS,
    targetFingers: [],
    unlockAfter: [],
    content: 'z x c v b n m , . / zx cv bn m, .z xc vb nm ,./ comma zebra virus cabin',
  },
  {
    level: 6, order: 6, section: 1,
    title: 'Bottom Row Words',
    description: 'Words from the bottom row.',
    difficulty: Difficulty.BEGINNER, targetWpm: 20, minAccuracy: 92,
    exerciseType: ExerciseType.WORDS,
    targetFingers: [],
    unlockAfter: [],
    content: 'zoom vacuum cabin minor comic camel bamboo zinc vibe maximum minimum banana',
  },
  {
    level: 7, order: 7, section: 1,
    title: 'All Rows Blend',
    description: 'Mix home, top, and bottom rows.',
    difficulty: Difficulty.BEGINNER, targetWpm: 22, minAccuracy: 92,
    exerciseType: ExerciseType.WORDS,
    targetFingers: [],
    unlockAfter: [],
    content: 'the quick brown fox jumps over the lazy dog pack my box with five dozen',
  },
  {
    level: 8, order: 8, section: 1,
    title: 'Punctuation Basics',
    description: 'Period, comma, and question mark.',
    difficulty: Difficulty.BEGINNER, targetWpm: 20, minAccuracy: 90,
    exerciseType: ExerciseType.SENTENCES,
    targetFingers: [],
    unlockAfter: [],
    content: 'Hello, world. How are you? The cat sat. We went home. Time flies, does it not?',
  },
  {
    level: 9, order: 9, section: 1,
    title: 'Short Sentences',
    description: 'Type clean, simple sentences.',
    difficulty: Difficulty.BEGINNER, targetWpm: 22, minAccuracy: 93,
    exerciseType: ExerciseType.SENTENCES,
    targetFingers: [],
    unlockAfter: [],
    content: 'A small step is still a step. Read the book. Open the door. The sun is warm.',
  },
  {
    level: 10, order: 10, section: 1,
    title: 'Numbers Row',
    description: 'The number row from 1 to 0.',
    difficulty: Difficulty.BEGINNER, targetWpm: 20, minAccuracy: 90,
    exerciseType: ExerciseType.KEYS,
    targetFingers: [],
    unlockAfter: [],
    content: '1 2 3 4 5 6 7 8 9 0 12 34 56 78 90 123 456 789 0 102 938',
  },
  {
    level: 11, order: 11, section: 1,
    title: 'Mixed Alphanumeric',
    description: 'Blend letters and digits.',
    difficulty: Difficulty.INTERMEDIATE, targetWpm: 22, minAccuracy: 92,
    exerciseType: ExerciseType.WORDS,
    targetFingers: [],
    unlockAfter: [],
    content: 'room 42 code 7 key 19 box 3 tag 88 win 5 run 12 day 60 top 9',
  },
  {
    level: 12, order: 12, section: 1, isCheckpoint: true,
    title: 'Foundation Checkpoint',
    description: 'A checkpoint that mixes everything you have learned.',
    difficulty: Difficulty.INTERMEDIATE, targetWpm: 24, minAccuracy: 94,
    exerciseType: ExerciseType.SENTENCES,
    targetFingers: [],
    unlockAfter: [],
    content: 'The quick brown fox jumps over the lazy dog, then ran home at 7 pm. Well done!',
  },
];

// ============================================================================
// SECTION 2: SKILL BUILDING (Levels 21-32) — common words, rhythm, accuracy
// ============================================================================

const section2Raw = [
  {
    level: 21, order: 1, section: 2,
    title: 'Most Common Words',
    description: 'The hundred most frequent English words.',
    difficulty: Difficulty.BEGINNER, targetWpm: 25, minAccuracy: 94,
    exerciseType: ExerciseType.WORDS,
    targetFingers: [],
    unlockAfter: [],
    content: 'the be to of and a in that have i it for not on with he as you do at this but his',
  },
  {
    level: 22, order: 2, section: 2,
    title: 'Two-Letter Words',
    description: 'Quick two-letter combinations build speed.',
    difficulty: Difficulty.BEGINNER, targetWpm: 28, minAccuracy: 95,
    exerciseType: ExerciseType.WORDS,
    targetFingers: [],
    unlockAfter: [],
    content: 'is it to go no on up so we he me be am an as at by do if in of ok',
  },
  {
    level: 23, order: 3, section: 2,
    title: 'Three-Letter Words',
    description: 'A stream of tidy three-letter words.',
    difficulty: Difficulty.BEGINNER, targetWpm: 28, minAccuracy: 95,
    exerciseType: ExerciseType.WORDS,
    targetFingers: [],
    unlockAfter: [],
    content: 'cat dog sun run bat box red pin map cup top lip fog nut web fix joy',
  },
  {
    level: 24, order: 4, section: 2,
    title: 'Bigrams Drill',
    description: 'Common letter pairs for finger flow.',
    difficulty: Difficulty.INTERMEDIATE, targetWpm: 30, minAccuracy: 95,
    exerciseType: ExerciseType.KEYS,
    targetFingers: [],
    unlockAfter: [],
    content: 'th er on an re he in ed nd ha at en es of or nt ea ti to ns',
  },
  {
    level: 25, order: 5, section: 2,
    title: 'Capital Letters',
    description: 'Shift to capitalize properly.',
    difficulty: Difficulty.INTERMEDIATE, targetWpm: 26, minAccuracy: 94,
    exerciseType: ExerciseType.WORDS,
    targetFingers: [],
    unlockAfter: [],
    content: 'The Big Red Fox Jumped Over The Lazy Dog New York Tokyo Paris London Rome',
  },
  {
    level: 26, order: 6, section: 2,
    title: 'Everyday Sentences',
    description: 'Plain sentences about daily life.',
    difficulty: Difficulty.INTERMEDIATE, targetWpm: 28, minAccuracy: 95,
    exerciseType: ExerciseType.SENTENCES,
    targetFingers: [],
    unlockAfter: [],
    content: 'She made coffee and read the news. He walked the dog before work. We cooked dinner.',
  },
  {
    level: 27, order: 7, section: 2,
    title: 'Questions and Answers',
    description: 'Practice punctuation with dialogue.',
    difficulty: Difficulty.INTERMEDIATE, targetWpm: 28, minAccuracy: 95,
    exerciseType: ExerciseType.SENTENCES,
    targetFingers: [],
    unlockAfter: [],
    content: 'What time is it? It is almost nine. Where are you going? To the market, then home.',
  },
  {
    level: 28, order: 8, section: 2,
    title: 'Email Snippets',
    description: 'Short professional phrases.',
    difficulty: Difficulty.INTERMEDIATE, targetWpm: 30, minAccuracy: 96,
    exerciseType: ExerciseType.SENTENCES,
    targetFingers: [],
    unlockAfter: [],
    content: 'Please find the report attached. Let me know if you have questions. Thanks for your help.',
  },
  {
    level: 29, order: 9, section: 2,
    title: 'Transitions',
    description: 'Linking words for fluent typing.',
    difficulty: Difficulty.INTERMEDIATE, targetWpm: 30, minAccuracy: 96,
    exerciseType: ExerciseType.WORDS,
    targetFingers: [],
    unlockAfter: [],
    content: 'however therefore although because meanwhile otherwise furthermore instead suddenly finally',
  },
  {
    level: 30, order: 10, section: 2,
    title: 'Quotes',
    description: 'Famous short quotes with punctuation.',
    difficulty: Difficulty.INTERMEDIATE, targetWpm: 30, minAccuracy: 96,
    exerciseType: ExerciseType.SENTENCES,
    targetFingers: [],
    unlockAfter: [],
    content: 'Stay hungry, stay foolish. "Knowledge is power." Well begun is half done. Less is more.',
  },
  {
    level: 31, order: 11, section: 2,
    title: 'Long Words',
    description: 'Stretch your fingers with longer vocabulary.',
    difficulty: Difficulty.INTERMEDIATE, targetWpm: 28, minAccuracy: 95,
    exerciseType: ExerciseType.WORDS,
    targetFingers: [],
    unlockAfter: [],
    content: 'beautiful wonderful manufacturer environment experience respiratory fluorescent circumstance',
  },
  {
    level: 32, order: 12, section: 2, isCheckpoint: true,
    title: 'Skill Building Checkpoint',
    description: 'A mixed checkpoint of words and sentences.',
    difficulty: Difficulty.INTERMEDIATE, targetWpm: 32, minAccuracy: 96,
    exerciseType: ExerciseType.SENTENCES,
    targetFingers: [],
    unlockAfter: [],
    content: 'The quiet library was full of wonderful books, and the old cat slept through every story.',
  },
];

// ============================================================================
// SECTION 3: ADVANCED TECHNIQUES (Levels 41-50) — sentences, symbols, flow
// ============================================================================

const section3Raw = [
  {
    level: 41, order: 1, section: 3,
    title: 'Punctuation Mastery',
    description: 'Commas, periods, colons, and semicolons.',
    difficulty: Difficulty.INTERMEDIATE, targetWpm: 30, minAccuracy: 95,
    exerciseType: ExerciseType.SENTENCES,
    targetFingers: [],
    unlockAfter: [],
    content: 'We ate; then we left. He said, "Wait." The rule is clear: practice daily, rest weekly.',
  },
  {
    level: 42, order: 2, section: 3,
    title: 'Parentheses and Quotes',
    description: 'Nested punctuation for technical writing.',
    difficulty: Difficulty.INTERMEDIATE, targetWpm: 30, minAccuracy: 95,
    exerciseType: ExerciseType.SENTENCES,
    targetFingers: [],
    unlockAfter: [],
    content: 'The function (see note) returned "ok". He asked ("are you sure?") and then continued.',
  },
  {
    level: 43, order: 3, section: 3,
    title: 'Symbol Row',
    description: 'Hyphens, equals, brackets, and slashes.',
    difficulty: Difficulty.INTERMEDIATE, targetWpm: 28, minAccuracy: 94,
    exerciseType: ExerciseType.KEYS,
    targetFingers: [],
    unlockAfter: [],
    content: ' - = [ ] { } / \\ | ; : \' " < > ~ ` ! @ # $ % ^ & * ( ) _ +',
  },
  {
    level: 44, order: 4, section: 3,
    title: 'Email Addresses',
    description: 'Type realistic email and url shapes.',
    difficulty: Difficulty.INTERMEDIATE, targetWpm: 28, minAccuracy: 94,
    exerciseType: ExerciseType.WORDS,
    targetFingers: [],
    unlockAfter: [],
    content: 'user@example.com support@site.org admin@team.io https://docs.site.io/guide',
  },
  {
    level: 45, order: 5, section: 3,
    title: 'Narrative Paragraph',
    description: 'A short descriptive paragraph.',
    difficulty: Difficulty.ADVANCED, targetWpm: 32, minAccuracy: 96,
    exerciseType: ExerciseType.PARAGRAPHS,
    targetFingers: [],
    unlockAfter: [],
    content: 'The train pulled away as rain began to fall. She watched the lights blur into streaks of gold, then turned up her collar and smiled at no one in particular.',
  },
  {
    level: 46, order: 6, section: 3,
    title: 'Technical Writing',
    description: 'Concise technical sentences.',
    difficulty: Difficulty.ADVANCED, targetWpm: 32, minAccuracy: 96,
    exerciseType: ExerciseType.SENTENCES,
    targetFingers: [],
    unlockAfter: [],
    content: 'Restart the service, then verify the health check. If latency rises, scale the workers horizontally.',
  },
  {
    level: 47, order: 7, section: 3,
    title: 'Lists and Steps',
    description: 'Numbered instructions and bullets.',
    difficulty: Difficulty.ADVANCED, targetWpm: 32, minAccuracy: 96,
    exerciseType: ExerciseType.SENTENCES,
    targetFingers: [],
    unlockAfter: [],
    content: '1. Open the file. 2. Edit the config. 3. Save and exit. 4. Run the tests. 5. Ship it.',
  },
  {
    level: 48, order: 8, section: 3,
    title: 'Complex Sentences',
    description: 'Longer clauses with mixed punctuation.',
    difficulty: Difficulty.ADVANCED, targetWpm: 34, minAccuracy: 96,
    exerciseType: ExerciseType.SENTENCES,
    targetFingers: [],
    unlockAfter: [],
    content: 'Although the deadline loomed, the team stayed calm; they had rehearsed the rollout, and nothing surprised them.',
  },
  {
    level: 49, order: 9, section: 3,
    title: 'Code-Like Prose',
    description: 'Snake_case and camelCase identifiers.',
    difficulty: Difficulty.ADVANCED, targetWpm: 32, minAccuracy: 95,
    exerciseType: ExerciseType.WORDS,
    targetFingers: [],
    unlockAfter: [],
    content: 'user_id first_name getUserName max_retry_count parse_config buildPipeline renderOutput',
  },
  {
    level: 50, order: 10, section: 3, isCheckpoint: true,
    title: 'Advanced Checkpoint',
    description: 'A demanding paragraph to cap the section.',
    difficulty: Difficulty.ADVANCED, targetWpm: 36, minAccuracy: 97,
    exerciseType: ExerciseType.PARAGRAPHS,
    targetFingers: [],
    unlockAfter: [],
    content: 'Good typing is invisible: the mind moves straight from thought to text. Practice slowly, then let speed follow accuracy; the rhythm, once earned, rarely leaves you.',
  },
];

// Attach derived keys to every lesson so the "keys to practice" list is exact.
export const section1Lessons = section1Raw.map((l) => ({ ...l, keys: deriveKeys(l.content) }));
export const section2Lessons = section2Raw.map((l) => ({ ...l, keys: deriveKeys(l.content) }));
export const section3Lessons = section3Raw.map((l) => ({ ...l, keys: deriveKeys(l.content) }));
