/* eslint-disable no-console */
import { Difficulty, ExerciseType } from '@prisma/client';
import { deriveKeys } from './seed-utils';

// ============================================================================
// SECTION 7: PYTHON CODING (Levels 101-110)
// ============================================================================

const pythonLessons = [
  {
    level: 101, order: 1, section: 7,
    title: 'Python: Hello, World!',
    description: 'Your first Python print.',
    difficulty: Difficulty.BEGINNER, targetWpm: 35, minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [], unlockAfter: [],
    content: 'print("Hello, World!")\nprint("Welcome to Python.")',
  },
  {
    level: 102, order: 2, section: 7,
    title: 'Python: Variables',
    description: 'Assign and interpolate values.',
    difficulty: Difficulty.BEGINNER, targetWpm: 35, minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [], unlockAfter: [],
    content: 'name = "Ada"\nage = 36\nprint(f"{name} is {age} years old.")',
  },
  {
    level: 103, order: 3, section: 7,
    title: 'Python: Lists',
    description: 'Build and loop over a list.',
    difficulty: Difficulty.BEGINNER, targetWpm: 36, minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [], unlockAfter: [],
    content: 'fruits = ["apple", "pear", "plum"]\nfor fruit in fruits:\n    print(fruit)',
  },
  {
    level: 104, order: 4, section: 7,
    title: 'Python: Conditionals',
    description: 'Branch on a condition.',
    difficulty: Difficulty.INTERMEDIATE, targetWpm: 36, minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [], unlockAfter: [],
    content: 'score = 87\nif score >= 90:\n    grade = "A"\nelse:\n    grade = "B"\nprint(grade)',
  },
  {
    level: 105, order: 5, section: 7,
    title: 'Python: Functions',
    description: 'Define and call a function.',
    difficulty: Difficulty.INTERMEDIATE, targetWpm: 37, minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [], unlockAfter: [],
    content: 'def square(n):\n    return n * n\n\nprint(square(4))',
  },
  {
    level: 106, order: 6, section: 7,
    title: 'Python: Dictionaries',
    description: 'Key-value maps.',
    difficulty: Difficulty.INTERMEDIATE, targetWpm: 37, minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [], unlockAfter: [],
    content: 'user = {"name": "Sam", "active": True}\nif user["active"]:\n    print(user["name"])',
  },
  {
    level: 107, order: 7, section: 7,
    title: 'Python: List Comprehension',
    description: 'Compact transforms.',
    difficulty: Difficulty.ADVANCED, targetWpm: 37, minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [], unlockAfter: [],
    content: 'nums = [1, 2, 3, 4]\nsquares = [n * n for n in nums]\nprint(squares)',
  },
  {
    level: 108, order: 8, section: 7,
    title: 'Python: File Read',
    description: 'Read a file safely.',
    difficulty: Difficulty.ADVANCED, targetWpm: 37, minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [], unlockAfter: [],
    content: 'with open("data.txt") as f:\n    for line in f:\n        print(line.strip())',
  },
  {
    level: 109, order: 9, section: 7,
    title: 'Python: Try/Except',
    description: 'Handle errors gracefully.',
    difficulty: Difficulty.ADVANCED, targetWpm: 38, minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [], unlockAfter: [],
    content: 'try:\n    value = int(input("n: "))\nexcept ValueError:\n    print("not a number")',
  },
  {
    level: 110, order: 10, section: 7, isCheckpoint: true,
    title: 'Python: Checkpoint',
    description: 'A small working routine.',
    difficulty: Difficulty.ADVANCED, targetWpm: 40, minAccuracy: 96,
    exerciseType: ExerciseType.CODE,
    targetFingers: [], unlockAfter: [],
    content: 'def total(nums):\n    return sum(nums)\n\nprint(total([1, 2, 3, 4, 5]))',
  },
];

// ============================================================================
// SECTION 8: JAVA CODING (Levels 126-135)
// ============================================================================

const javaLessons = [
  {
    level: 126, order: 1, section: 8,
    title: 'Java: Hello, World!',
    description: 'A minimal Java program.',
    difficulty: Difficulty.BEGINNER, targetWpm: 35, minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [], unlockAfter: [],
    content: 'public class Main {\n    public static void main(String[] args) {\n        System.out.println("Hello, World!");\n    }\n}',
  },
  {
    level: 127, order: 2, section: 8,
    title: 'Java: Variables',
    description: 'Typed declarations.',
    difficulty: Difficulty.BEGINNER, targetWpm: 35, minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [], unlockAfter: [],
    content: 'int age = 36;\nString name = "Ada";\nSystem.out.println(name + " " + age);',
  },
  {
    level: 128, order: 3, section: 8,
    title: 'Java: Arrays',
    description: 'Declare and iterate an array.',
    difficulty: Difficulty.BEGINNER, targetWpm: 36, minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [], unlockAfter: [],
    content: 'int[] nums = {1, 2, 3};\nfor (int n : nums) {\n    System.out.println(n);\n}',
  },
  {
    level: 129, order: 4, section: 8,
    title: 'Java: Conditionals',
    description: 'If-else branching.',
    difficulty: Difficulty.INTERMEDIATE, targetWpm: 36, minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [], unlockAfter: [],
    content: 'int score = 87;\nif (score >= 90) {\n    System.out.println("A");\n} else {\n    System.out.println("B");\n}',
  },
  {
    level: 130, order: 5, section: 8,
    title: 'Java: Methods',
    description: 'Define a method.',
    difficulty: Difficulty.INTERMEDIATE, targetWpm: 37, minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [], unlockAfter: [],
    content: 'static int square(int n) {\n    return n * n;\n}\n\nSystem.out.println(square(4));',
  },
  {
    level: 131, order: 6, section: 8,
    title: 'Java: ArrayList',
    description: 'A dynamic list.',
    difficulty: Difficulty.INTERMEDIATE, targetWpm: 37, minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [], unlockAfter: [],
    content: 'ArrayList<String> list = new ArrayList<>();\nlist.add("apple");\nlist.add("pear");\nSystem.out.println(list.size());',
  },
  {
    level: 132, order: 7, section: 8,
    title: 'Java: Loops',
    description: 'While and for loops.',
    difficulty: Difficulty.ADVANCED, targetWpm: 37, minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [], unlockAfter: [],
    content: 'int i = 0;\nwhile (i < 5) {\n    System.out.println(i);\n    i++;\n}',
  },
  {
    level: 133, order: 8, section: 8,
    title: 'Java: HashMap',
    description: 'A key-value map.',
    difficulty: Difficulty.ADVANCED, targetWpm: 37, minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [], unlockAfter: [],
    content: 'Map<String, Integer> m = new HashMap<>();\nm.put("a", 1);\nSystem.out.println(m.get("a"));',
  },
  {
    level: 134, order: 9, section: 8,
    title: 'Java: Try/Catch',
    description: 'Catch an exception.',
    difficulty: Difficulty.ADVANCED, targetWpm: 38, minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [], unlockAfter: [],
    content: 'try {\n    int n = Integer.parseInt("x");\n} catch (NumberFormatException e) {\n    System.out.println("bad");\n}',
  },
  {
    level: 135, order: 10, section: 8, isCheckpoint: true,
    title: 'Java: Checkpoint',
    description: 'A small complete class.',
    difficulty: Difficulty.ADVANCED, targetWpm: 40, minAccuracy: 96,
    exerciseType: ExerciseType.CODE,
    targetFingers: [], unlockAfter: [],
    content: 'static int total(int[] ns) {\n    int s = 0;\n    for (int n : ns) s += n;\n    return s;\n}\n\nSystem.out.println(total(new int[]{1,2,3}));',
  },
];

// ============================================================================
// SECTION 9: C++ CODING (Levels 151-160)
// ============================================================================

const cppLessons = [
  {
    level: 151, order: 1, section: 9,
    title: 'C++: Hello, World!',
    description: 'A minimal C++ program.',
    difficulty: Difficulty.BEGINNER, targetWpm: 35, minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [], unlockAfter: [],
    content: '#include <iostream>\n\nint main() {\n    std::cout << "Hello, World!" << std::endl;\n    return 0;\n}',
  },
  {
    level: 152, order: 2, section: 9,
    title: 'C++: Variables',
    description: 'Typed declarations.',
    difficulty: Difficulty.BEGINNER, targetWpm: 35, minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [], unlockAfter: [],
    content: 'int age = 36;\nstd::string name = "Ada";\nstd::cout << name << " " << age << std::endl;',
  },
  {
    level: 153, order: 3, section: 9,
    title: 'C++: Vectors',
    description: 'A dynamic array.',
    difficulty: Difficulty.BEGINNER, targetWpm: 36, minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [], unlockAfter: [],
    content: '#include <vector>\nstd::vector<int> v = {1, 2, 3};\nv.push_back(4);\nstd::cout << v.size();',
  },
  {
    level: 154, order: 4, section: 9,
    title: 'C++: Conditionals',
    description: 'If-else branching.',
    difficulty: Difficulty.INTERMEDIATE, targetWpm: 36, minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [], unlockAfter: [],
    content: 'int score = 87;\nif (score >= 90) {\n    std::cout << "A";\n} else {\n    std::cout << "B";\n}',
  },
  {
    level: 155, order: 5, section: 9,
    title: 'C++: Functions',
    description: 'Declare and call a function.',
    difficulty: Difficulty.INTERMEDIATE, targetWpm: 37, minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [], unlockAfter: [],
    content: 'int square(int n) {\n    return n * n;\n}\n\nstd::cout << square(4);',
  },
  {
    level: 156, order: 6, section: 9,
    title: 'C++: Loops',
    description: 'For loop over a range.',
    difficulty: Difficulty.INTERMEDIATE, targetWpm: 37, minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [], unlockAfter: [],
    content: 'for (int i = 0; i < 5; i++) {\n    std::cout << i << std::endl;\n}',
  },
  {
    level: 157, order: 7, section: 9,
    title: 'C++: Classes',
    description: 'A simple class.',
    difficulty: Difficulty.ADVANCED, targetWpm: 37, minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [], unlockAfter: [],
    content: 'class Point {\npublic:\n    int x, y;\n};\nPoint p;\np.x = 3;',
  },
  {
    level: 158, order: 8, section: 9,
    title: 'C++: References',
    description: 'Pass by reference.',
    difficulty: Difficulty.ADVANCED, targetWpm: 37, minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [], unlockAfter: [],
    content: 'void add(int& n) { n += 1; }\n\nint v = 1;\nadd(v);\nstd::cout << v;',
  },
  {
    level: 159, order: 9, section: 9,
    title: 'C++: Map',
    description: 'A key-value map.',
    difficulty: Difficulty.ADVANCED, targetWpm: 38, minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [], unlockAfter: [],
    content: '#include <map>\nstd::map<std::string, int> m;\nm["a"] = 1;\nstd::cout << m["a"];',
  },
  {
    level: 160, order: 10, section: 9, isCheckpoint: true,
    title: 'C++: Checkpoint',
    description: 'A small complete program.',
    difficulty: Difficulty.ADVANCED, targetWpm: 40, minAccuracy: 96,
    exerciseType: ExerciseType.CODE,
    targetFingers: [], unlockAfter: [],
    content: 'int total(std::vector<int> v) {\n    int s = 0;\n    for (int n : v) s += n;\n    return s;\n}\n\nstd::cout << total({1, 2, 3});',
  },
];

// ============================================================================
// SECTION 10: C CODING (Levels 176-185)
// ============================================================================

const cLessons = [
  {
    level: 176, order: 1, section: 10,
    title: 'C: Hello, World!',
    description: 'A minimal C program.',
    difficulty: Difficulty.BEGINNER, targetWpm: 35, minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [], unlockAfter: [],
    content: '#include <stdio.h>\n\nint main() {\n    printf("Hello, World!\\n");\n    return 0;\n}',
  },
  {
    level: 177, order: 2, section: 10,
    title: 'C: Variables',
    description: 'Typed declarations.',
    difficulty: Difficulty.BEGINNER, targetWpm: 35, minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [], unlockAfter: [],
    content: 'int age = 36;\nchar* name = "Ada";\nprintf("%s %d\\n", name, age);',
  },
  {
    level: 178, order: 3, section: 10,
    title: 'C: Arrays',
    description: 'A fixed array.',
    difficulty: Difficulty.BEGINNER, targetWpm: 36, minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [], unlockAfter: [],
    content: 'int nums[3] = {1, 2, 3};\nfor (int i = 0; i < 3; i++) {\n    printf("%d\\n", nums[i]);\n}',
  },
  {
    level: 179, order: 4, section: 10,
    title: 'C: Conditionals',
    description: 'If-else branching.',
    difficulty: Difficulty.INTERMEDIATE, targetWpm: 36, minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [], unlockAfter: [],
    content: 'int score = 87;\nif (score >= 90) {\n    printf("A\\n");\n} else {\n    printf("B\\n");\n}',
  },
  {
    level: 180, order: 5, section: 10,
    title: 'C: Functions',
    description: 'Declare and call a function.',
    difficulty: Difficulty.INTERMEDIATE, targetWpm: 37, minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [], unlockAfter: [],
    content: 'int square(int n) {\n    return n * n;\n}\n\nprintf("%d\\n", square(4));',
  },
  {
    level: 181, order: 6, section: 10,
    title: 'C: Loops',
    description: 'While loop.',
    difficulty: Difficulty.INTERMEDIATE, targetWpm: 37, minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [], unlockAfter: [],
    content: 'int i = 0;\nwhile (i < 5) {\n    printf("%d\\n", i);\n    i++;\n}',
  },
  {
    level: 182, order: 7, section: 10,
    title: 'C: Pointers',
    description: 'Address and dereference.',
    difficulty: Difficulty.ADVANCED, targetWpm: 37, minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [], unlockAfter: [],
    content: 'int v = 1;\nint* p = &v;\n*p = 2;\nprintf("%d\\n", v);',
  },
  {
    level: 183, order: 8, section: 10,
    title: 'C: Strings',
    description: 'A character array.',
    difficulty: Difficulty.ADVANCED, targetWpm: 37, minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [], unlockAfter: [],
    content: 'char name[8] = "Ada";\nprintf("%s\\n", name);',
  },
  {
    level: 184, order: 9, section: 10,
    title: 'C: Structs',
    description: 'A simple struct.',
    difficulty: Difficulty.ADVANCED, targetWpm: 38, minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [], unlockAfter: [],
    content: 'typedef struct { int x; int y; } Point;\nPoint p = {3, 4};\nprintf("%d\\n", p.x);',
  },
  {
    level: 185, order: 10, section: 10, isCheckpoint: true,
    title: 'C: Checkpoint',
    description: 'A small complete program.',
    difficulty: Difficulty.ADVANCED, targetWpm: 40, minAccuracy: 96,
    exerciseType: ExerciseType.CODE,
    targetFingers: [], unlockAfter: [],
    content: 'int total(int* ns, int n) {\n    int s = 0;\n    for (int i = 0; i < n; i++) s += ns[i];\n    return s;\n}\n\nprintf("%d\\n", total((int[]){1,2,3}, 3));',
  },
];

export const codingLessons = [
  ...pythonLessons,
  ...javaLessons,
  ...cppLessons,
  ...cLessons,
].map((l) => ({ ...l, keys: deriveKeys(l.content) }));
