import { Difficulty, ExerciseType } from '@prisma/client';

export type LessonSeed = {
  level: number;
  order: number;
  section: number;
  title: string;
  description: string;
  keys: string[];
  difficulty: Difficulty;
  targetWpm: number;
  minAccuracy: number;
  exerciseType: ExerciseType;
  targetFingers: string[];
  unlockAfter: number[];
  content: string;
  isCheckpoint?: boolean;
};

/**
 * Derive the set of keys a lesson drills directly from its content.
 * This keeps `keys` consistent (the old hand-written lists were noisy/incomplete),
 * so the "keys to practice" UI and any key-based logic always match the text.
 */
export function deriveKeys(content: string): string[] {
  const seen = new Set<string>();
  for (const ch of content.toLowerCase()) seen.add(ch);
  return [...seen];
}

// ---------------------------------------------------------------------------
// Curated intent-based titles per section (what you DO, not content slice)
// Must be distinct per lesson. Fallback pattern used if array shorter than contents.
// ---------------------------------------------------------------------------
const titlesBySection: Record<number, string[]> = {
  1: [
    'Home Row Foundations: Anchor Position',
    'Home Row Words: Fall & Flask',
    'Top Row Intro: QWERTY Reach',
    'Top Row Flow: Quiet & Type',
    'Home Row Reset: ASDF Cycle',
    'Reverse Drill: LKJH Return',
    'Row Integration: QWER + ASDF + ZXCV',
    'Repetition Drill: Pat Tempo',
    'Repetition Drill: Jump Lift',
    'Repetition Drill: Drink Flow',
    'Repetition Drill: Flank Stretch',
    'Repetition Drill: Glance Rhythm',
    'Word Stamina: Brave',
    'Word Stamina: Craft',
    'Word Stamina: Drain',
    'Word Stamina: Flask',
    'Word Stamina: Grace',
    'Endurance: Harvest',
    'Endurance: Journey',
    'Endurance: Kiln',
    'Endurance: Lamp',
    'Endurance: Machine',
    'Endurance: Nest',
    'Endurance: Ocean',
  ],
  2: [
    'Skill Reset: Home Row Words',
    'Home Row Flow: ASDF ↔ JKL; Cycle',
    'Reverse Flow: LKJH Drill',
    'Row Integration: All Rows',
    'Cadence Drill: Pat',
    'Cadence Drill: Jump',
    'Cadence Drill: Drink',
    'Cadence Drill: Flank',
    'Cadence Drill: Glance',
    'Word Stamina: Brave',
    'Word Stamina: Craft',
    'Word Stamina: Drain',
    'Word Stamina: Flask',
    'Word Stamina: Grace',
    'Word Stamina: Harvest',
    'Word Stamina: Journey',
    'Word Stamina: Kiln',
    'Word Stamina: Lamp',
    'Word Stamina: Machine',
    'Word Stamina: Nest',
    'Word Stamina: Ocean',
    'Alphabet Focus: Quartz',
    'Alphabet Focus: Rust',
    'Alphabet Focus: Salt',
    'Alphabet Focus: Tent',
    'Alphabet Focus: Ultra',
    'Alphabet Focus: Vessel',
    'Alphabet Focus: Whale',
    'Alphabet Focus: Xenon',
    'Alphabet Focus: Yield',
    'Alphabet Focus: Zest',
    'Pangram: Quick Brown Fox',
    'Pangram: Five Dozen Liquor Jugs',
    'Pangram: Vexingly Quick Zebras',
    'Pangram: Bright Vixens & Dozy Fowl',
    'Pangram: Sphinx of Black Quartz',
  ],
  3: [
    'Top Row Recall: QWERTY Flow',
    'Home Row Recall: ASDF Reset',
    'Reverse Recall: LKJH',
    'Integration Drill: Rows Combined',
    'Speed Burst: Pat',
    'Speed Burst: Jump',
    'Speed Burst: Drink',
    'Speed Burst: Flank',
    'Speed Burst: Glance',
    'Speed Burst: Brave',
    'Speed Burst: Craft',
    'Speed Burst: Drain',
    'Speed Burst: Flask',
    'Speed Burst: Grace',
    'Endurance: Harvest',
    'Endurance: Journey',
    'Endurance: Kiln',
    'Endurance: Lamp',
    'Endurance: Machine',
    'Endurance: Nest',
    'Endurance: Ocean',
    'Endurance: Quartz',
    'Endurance: Rust',
    'Endurance: Salt',
    'Endurance: Tent',
    'Endurance: Ultra',
    'Endurance: Vessel',
    'Endurance: Whale',
    'Endurance: Xenon',
    'Endurance: Yield',
    'Endurance: Zest',
    'Pangram Mastery: Quick Brown Fox',
    'Pangram Mastery: Liquor Jugs',
    'Pangram Mastery: Vexing Zebras',
    'Pangram Mastery: Bright Vixens',
    'Pangram Mastery: Sphinx Quartz',
    'Latin Flow: Lorem Ipsum Opening',
    'Latin Flow: Eiusmod Tempor',
    'Latin Flow: Minim Veniam',
    'Latin Flow: Dolor in Voluptate',
    'Latin Flow: Culpa & Laborum Finale',
  ],
  4: [
    'High-Frequency Words: The & That',
    'Suffix Patterns: -tion & -ing',
    'Prose Flow: Wind & Lake',
    'News Brief: Markets & Earnings',
    'Dialogue Punctuation: Quotes & Replies',
    'Marketing Copy: Speed & Focus',
    'Dev Config: Keys & Tokens',
    'Team Narrative: Ship & Fix',
    'Log Entry: Order & Token Status',
    'Reflective Prose: Speed Follows Accuracy',
    'Rhythm: Hands Learn the Board',
    'Rhythm: Daily Practice Builds Memory',
    'Rhythm: Market Closed Higher',
    'Rhythm: Error Rate Fell',
    'Rhythm: Read the Prompt Carefully',
    'Rhythm: Server Restarted at Dawn',
    'Rhythm: Short Walk & Water',
    'Rhythm: Quick Brown Fox Revisited',
    'Rhythm: Client Requests & Queue',
    'Rhythm: Meeting Notes & Follow-ups',
    'Anchor Drill: Home Row Return',
    'Ambient Prose: City at Night',
    'Product Note: Version Two Launched',
    'Under Pressure: Slow by Five Percent',
    'Clarity Drill: Clear Email & Reply',
  ],
  5: [
    'Caching Concepts: Hits & Misses',
    'Step-by-Step: Project Setup',
    'Business Memo: Q3 Plan',
    'Narrative: Lighthouse Keeper',
    'Spec Draft: JSON & Latency',
    'Argument: Invest Now',
    'Science Note: Photosynthesis',
    'Mindset: Speed of Recovery',
    'Paragraph: Proposal Passed',
    'Paragraph: Steady Gains Compound',
    'Paragraph: Library Reopened',
    'Paragraph: Good Apology',
    'Paragraph: Contract & Notary',
    'Paragraph: Notebook by Keyboard',
    'Paragraph: Mountain Trail',
    'Paragraph: Reliability via Simplicity',
    'Paragraph: Museum Guide Pauses',
    'Paragraph: Support Tickets Stopped',
    'Paragraph: Winter Storm & Generators',
    'Drafting: Edit with Fresh Eyes',
    'Negotiation: State Needs',
    'Report: Concise & Honest',
    'Habit: Steady Routine Beats Heroics',
    'Revision: Second Draft Shorter',
    'Mindset: Comfortably Below Limit',
  ],
  6: [
    'Variables & Literals: Count & Name',
    'Conditionals & Loops: If & For',
    'Functions: Define & Call',
    'Data Structures: Dict & Queue',
    'Recursion: Factorial',
    'Loop Filter: Even Check',
    'Error Handling: Try/Except File',
    'Math Module: Sqrt & Pi',
    'Classes: Dog & Init',
    'Comprehension: Double Evens',
    'JSON: Dumps & Struct',
    'Aggregation: Average from List',
    'String Ops: Upper & Split',
    'Dict Ops: Insert & Keys',
    'File Write: With Open',
    'Regex: Find Digits',
    'Datetime: Now ISO',
    'Sorting: Array Ascending',
    'Defaults: Greet with Default',
    'Swapping: Tuple Assignment',
    'Logic: And/Or/Not',
    'Sets: Add & Membership',
    'Tuples: Unpack & Sum',
    'Number Bases: Hex/Bin/Oct',
    'String Check: Isnumeric & Isalpha',
  ],
  7: [
    'Python: Hello World Print',
    'Python: Input & Greeting',
    'Python: For Loop with Range',
    'Python: Typed Function & Return',
    'Python: List Sum & Average',
    'Python: File Read & List Comprehension',
    'Python: Try/Except Value Handling',
    'Python: Math Module Power & Root',
    'Python: Class Init & Method',
    'Python: List Comprehension Filter',
    'Python: JSON Dumps & Serialization',
    'Python: Datetime Formatting',
    'Python: Regex Findall Patterns',
    'Python: NumPy Array Mean',
    'Python: Pandas DataFrame Describe',
    'Python: Async Await Fetch',
    'Python: Lambda Functions',
    'Python: Sets & Uniqueness',
    'Python: Map & Upper Transform',
    'Python: Enumerate & Formatting',
    'Python: Dict Merge & Unpacking',
    'Python: Number Base Conversions',
    'Python: Ternary & Status Check',
    'Python: Sorting & Reverse',
    'Python: Counter & Frequency',
    'Python: Pathlib & File Paths',
    'Python: Generator & Fibonacci',
    'Python: Dict Get & Conditionals',
    'Python: Dict Values & Aggregation',
    'Python: Sort & Slice Top Scores',
  ],
  8: [
    'Java: Hello World Class',
    'Java: Variables & Arithmetic',
    'Java: String Formatting',
    'Java: For Loop Iteration',
    'Java: Arrays & Stream Sum',
    'Java: Try-with-Resources File Read',
    'Java: Math Sqrt & Pow',
    'Java: Class & Constructor',
    'Java: List & Filter Loop',
    'Java: Map & Merge',
    'Java: LocalDate Formatting',
    'Java: Regex Pattern Matching',
    'Java: Record & Hypotenuse',
    'Java: Logging with Instant',
    'Java: Stream Filter & ForEach',
    'Java: String Join CSV',
    'Java: Hex Parse & Format',
    'Java: Binary Parse & Format',
    'Java: Octal Parse & Format',
    'Java: String Validation',
    'Java: IntStream & Map',
    'Java: Stream Map Uppercase',
    'Java: Optional Handling',
    'Java: Duration & Instants',
    'Java: DateTime Formatting',
    'Java: Enum & Status',
    'Java: CompletableFuture Async',
    'Java: GroupingBy Collector',
    'Java: Sealed Interface & Records',
    'Java: HttpRequest Builder',
  ],
  9: [
    'C++: Hello World I/O',
    'C++: Variables & Ratio',
    'C++: String Concatenation',
    'C++: For Loop Output',
    'C++: Vector & Accumulate Sum',
    'C++: File Input & Lines',
    'C++: Exception Handling',
    'C++: Cmath Root & Power',
    'C++: Class & Constructor',
    'C++: Vector Filter & Push',
    'C++: HashMap Insert & Lookup',
    'C++: Chrono & System Time',
    'C++: Regex Search',
    'C++: Array Mean',
    'C++: File Output Stream',
    'C++: Lambda Capture',
    'C++: Set Uniqueness',
    'C++: Map Lookup',
    'C++: String to Int Conversion',
    'C++: Join Strings to CSV',
    'C++: Hex & Decimal Output',
    'C++: Bitset Binary View',
    'C++: Octal Output',
    'C++: All_of & Digit Check',
    'C++: Sort Descending',
    'C++: Iota & Product',
    'C++: MinMax Element',
    'C++: Optional Handling',
    'C++: Filesystem Exists',
    'C++: Struct & Hypotenuse',
  ],
  10: [
    'C: Hello World Printf',
    'C: Variables & Ratio',
    'C: String Format with Snprintf',
    'C: For Loop & Print',
    'C: Array Sum Loop',
    'C: File Open & Read',
    'C: Safe Divide & Error Handling',
    'C: Math Sqrt & Pow',
    'C: Struct & Initialization',
    'C: Array Filter & Index',
    'C: String Key & Value',
    'C: Time & Localtime',
    'C: Regex Compile & Exec',
    'C: Array Mean Calculation',
    'C: File Write',
    'C: Function & Return',
    'C: Unique Count Loop',
    'C: Struct Entry & Print',
    'C: Atoi & Snprintf Convert',
    'C: CSV Join with Strcat',
    'C: Hex & Decimal Print',
    'C: Bits & Putchar Loop',
    'C: Octal Print',
    'C: Digit Check Loop',
    'C: Qsort & Comparator',
    'C: Array Product Loop',
    'C: Min & Max Scan',
    'C: Ternary & Null Check',
    'C: Stat & File Exists',
    'C: Struct Point & Hypot',
  ],
};

const descriptionsBySection: Record<number, string[]> = {
  1: [
    'Anchor fingers on home row and reset cleanly between reaches.',
    'Build flow on common home-row words like fall and flask.',
    'Reach for the top row QWERTY keys with light taps.',
    'Type frequent top-row words with steady rhythm.',
    'Cycle asdf ↔ jkl; to lock in home position.',
    'Reverse drill: return from semicolon row with control.',
    'Integrate QWER, ASDF, and ZXCV in vertical scans.',
    'Hold even tempo on repeated pat strokes.',
    'Lift and land cleanly on jump repetitions.',
    'Keep flow smooth on drink repetitions.',
    'Stretch for flank while keeping wrists neutral.',
    'Maintain rhythm on glance repetitions.',
    'Stamina drill centered on brave.',
    'Stamina drill centered on craft.',
    'Stamina drill centered on drain.',
    'Stamina drill centered on flask.',
    'Stamina drill centered on grace.',
    'Sustain accuracy through harvest repetitions.',
    'Sustain accuracy through journey repetitions.',
    'Sustain accuracy through kiln repetitions.',
    'Sustain accuracy through lamp repetitions.',
    'Sustain accuracy through machine repetitions.',
    'Sustain accuracy through nest repetitions.',
    'Sustain accuracy through ocean repetitions.',
  ],
  2: [
    'Reset skill with familiar home-row words.',
    'Alternate asdf and jkl; for fluid hand balance.',
    'Reverse flow drill moving inward from the edges.',
    'Combine rows into one continuous scan.',
    'Tempo drill: repeat pat for cadence.',
    'Tempo drill: repeat jump for lift control.',
    'Tempo drill: repeat drink for flow.',
    'Tempo drill: repeat flank for stretch.',
    'Tempo drill: repeat glance for eye lead.',
    'Repetition focusing on brave form.',
    'Repetition focusing on craft form.',
    'Repetition focusing on drain form.',
    'Repetition focusing on flask form.',
    'Repetition focusing on grace form.',
    'Repetition focusing on harvest form.',
    'Repetition focusing on journey form.',
    'Repetition focusing on kiln form.',
    'Repetition focusing on lamp form.',
    'Repetition focusing on machine form.',
    'Repetition focusing on nest form.',
    'Repetition focusing on ocean form.',
    'Alphabet stretch with quartz patterns.',
    'Alphabet stretch with rust patterns.',
    'Alphabet stretch with salt patterns.',
    'Alphabet stretch with tent patterns.',
    'Alphabet stretch with ultra patterns.',
    'Alphabet stretch with vessel patterns.',
    'Alphabet stretch with whale patterns.',
    'Alphabet stretch with xenon patterns.',
    'Alphabet stretch with yield patterns.',
    'Alphabet stretch with zest patterns.',
    'Pangram covering the full alphabet in one sentence.',
    'Pangram with liquor jugs and five dozen mix.',
    'Pangram with vexing zebras and quick jumps.',
    'Pangram balancing vixens and dozy fowl.',
    'Pangram with sphinx and quartz judgment.',
  ],
  3: [
    'Recall top-row QWERTY flow under speed pressure.',
    'Recall home-row reset at higher tempo.',
    'Reverse recall checking semicolon control.',
    'Combine all rows without pausing.',
    'Burst speed on pat with clean returns.',
    'Burst speed on jump with clean returns.',
    'Burst speed on drink with clean returns.',
    'Burst speed on flank with clean returns.',
    'Burst speed on glance with clean returns.',
    'Burst speed on brave with clean returns.',
    'Burst speed on craft with clean returns.',
    'Burst speed on drain with clean returns.',
    'Burst speed on flask with clean returns.',
    'Burst speed on grace with clean returns.',
    'Endurance typing for harvest at rhythm.',
    'Endurance typing for journey at rhythm.',
    'Endurance typing for kiln at rhythm.',
    'Endurance typing for lamp at rhythm.',
    'Endurance typing for machine at rhythm.',
    'Endurance typing for nest at rhythm.',
    'Endurance typing for ocean at rhythm.',
    'Endurance typing for quartz at rhythm.',
    'Endurance typing for rust at rhythm.',
    'Endurance typing for salt at rhythm.',
    'Endurance typing for tent at rhythm.',
    'Endurance typing for ultra at rhythm.',
    'Endurance typing for vessel at rhythm.',
    'Endurance typing for whale at rhythm.',
    'Endurance typing for xenon at rhythm.',
    'Endurance typing for yield at rhythm.',
    'Endurance typing for zest at rhythm.',
    'Pangram mastery with quick brown fox.',
    'Pangram mastery with liquor jugs.',
    'Pangram mastery with vexing zebras.',
    'Pangram mastery with bright vixens.',
    'Pangram mastery with sphinx quartz.',
    'Fluent Latin prose: lorem ipsum opening.',
    'Fluent Latin prose: eiusmod tempor passage.',
    'Fluent Latin prose: minim veniam phrasing.',
    'Fluent Latin prose: voluptate dolore cadence.',
    'Fluent Latin prose: culpa and laborum finale.',
  ],
  4: [
    'Drill the most common English words at a clip.',
    'Practice slippery suffix patterns like tion and ing.',
    'Sustain prose rhythm through a natural scene.',
    'Type concise news briefs with proper nouns.',
    'Handle quotes and dialogue tags cleanly.',
    'Type marketing microcopy with short punchy sentences.',
    'Drill config keys and snake_case fluency.',
    'Narrate a shipped feature and bugfix arc.',
    'Parse mixed alphanumeric logs and tokens.',
    'Reflect on speed following accuracy like gravity.',
    'Train hands to find the board without eyes.',
    'Build muscle memory through short daily reps.',
    'Track a market narrative with steady pacing.',
    'Report an error-rate drop with numbers.',
    'Read ahead and correct with small, calm edits.',
    'Describe a server restart and green dashboard.',
    'Break for focus: walk and water over coffee.',
    'Revisit the pangram with controlled rhythm.',
    'Absorb burst arrivals through a queue metaphor.',
    'Capture concise meeting notes and next steps.',
    'Return to home row after every reach.',
    'Type ambient city-at-night prose evenly.',
    'Announce a version launch with fewer bugs.',
    'Slow by five percent when pressure spikes.',
    'Compose a clear subject and short body.',
  ],
  5: [
    'Explain caching trade-offs with precise punctuation.',
    'Give step-by-step setup instructions clearly.',
    'Summarize a Q3 plan in memo form.',
    'Render a lighthouse scene with literary rhythm.',
    'Write a service spec with latency constraints.',
    'Argue for early investment with data.',
    'Explain photosynthesis in plain language.',
    'Reflect on recovery speed over error absence.',
    'Report a proposal debate and optimism.',
    'Note how steady gains compound over spikes.',
    'Describe a reopened library and quiet room.',
    'Model a good apology that names the fix.',
    'Draft a contract with signatures and appendix.',
    'Log awkward words in a notebook by the keys.',
    'Describe a steep trail and ridge view.',
    'Define reliability through fewer surprises.',
    'Follow a museum guide who pauses for questions.',
    'Measure progress by tickets that stop arriving.',
    'Keep a service warm through a winter storm.',
    'Leave a draft overnight and edit with fresh eyes.',
    'Negotiate by stating needs over demands.',
    'Write a concise report naming key decisions.',
    'Prefer a steady routine to heroic marathons.',
    'Compare a shorter, clearer second draft.',
    'Type comfortably below your limit, for longer.',
  ],
  6: [
    'Declare variables and simple literals.',
    'Branch and loop with if/else and for.',
    'Define a function and call it with args.',
    'Work with dicts, lists, and queues.',
    'Implement recursive factorial cleanly.',
    'Filter a list for even values inside a loop.',
    'Handle missing files with try/except.',
    'Use the math module for sqrt and pi.',
    'Define a class with init and method.',
    'Comprehend doubles for even numbers.',
    'Serialize a payload with json dumps.',
    'Compute an average from sum and length.',
    'Transform strings with upper and split.',
    'Insert into a dict and list its keys.',
    'Write a file using with open.',
    'Find digits with a regex pattern.',
    'Format the current datetime as ISO.',
    'Sort an array in place.',
    'Provide a default argument for a function.',
    'Swap two values with tuple assignment.',
    'Combine conditions with and/or/not logic.',
    'Track uniqueness with a set.',
    'Unpack a tuple into variables.',
    'Convert among hex, bin, and oct.',
    'Check numeric and alphabetic string traits.',
  ],
  7: [
    'Print Hello World to standard output.',
    'Prompt for a name with input().',
    'Loop a fixed range and print each step.',
    'Declare a typed greet function and return a string.',
    'Sum a list and compute its average.',
    'Read stripped lines from a text file.',
    'Guard integer parsing with try/except.',
    'Compute sqrt and power with math.',
    'Model a Dog class with typed init and bark.',
    'Build evens with a filtered comprehension.',
    'Dump a payload to JSON with indent.',
    'Format the current datetime for display.',
    'Extract letter-digit tokens with regex.',
    'Compute a mean with NumPy.',
    'Describe a small DataFrame with pandas.',
    'Define an async fetch that sleeps briefly.',
    'Apply a lambda to square a number.',
    'Deduplicate with a set and sort the result.',
    'Uppercase words via map.',
    'Enumerate items with a formatted index.',
    'Merge two dicts with unpacking.',
    'Show hex, bin, and oct for a value.',
    'Branch on a ternary over a status check.',
    'Sort names alphabetically and reversed.',
    'Count frequencies with Counter.',
    'Check existence and name with Pathlib.',
    'Yield Fibonacci numbers from a generator.',
    'Branch on a dict role lookup.',
    'Aggregate values from a dict.',
    'Sort numbers descending and slice the top.',
  ],
  8: [
    'Run a classic Hello World main class.',
    'Compute a ratio from ints and doubles.',
    'Format a greeting string cleanly.',
    'Iterate with a classic for loop.',
    'Sum an int array via Arrays.stream.',
    'Read a line with try-with-resources.',
    'Compute sqrt and power with Math.',
    'Encapsulate name and breed in a class.',
    'Collect evens into an ArrayList with a loop.',
    'Merge counts into a HashMap.',
    'Format today as ISO date.',
    'Test a regex Pattern and Matcher.',
    'Use a record and hypot for distance.',
    'Log a message timestamped with Instant.',
    'Filter a stream and print matches.',
    'Join fields into a semicolon CSV.',
    'Round-trip hex parsing and formatting.',
    'Round-trip binary parsing and formatting.',
    'Round-trip octal parsing and formatting.',
    'Validate numeric and email substrings.',
    'Square numbers with an IntStream.',
    'Map strings to uppercase via streams.',
    'Unwrap an Optional with a default.',
    'Measure elapsed seconds with Duration.',
    'Format a LocalDateTime with a pattern.',
    'Branch on an enum status value.',
    'Chain a CompletableFuture and join.',
    'Group strings by first character.',
    'Model shapes with a sealed interface.',
    'Build an HttpRequest with a URI.',
  ],
  9: [
    'Emit Hello World with iostream.',
    'Compute a ratio from active users.',
    'Concatenate a greeting string.',
    'Loop and print an index prefix.',
    'Sum a vector with accumulate.',
    'Stream lines from an input file.',
    'Throw and catch a runtime error.',
    'Compute sqrt and pow with cmath.',
    'Define a class with const method.',
    'Push filtered evens into a vector.',
    'Store and read counts from an unordered_map.',
    'Capture system time with chrono.',
    'Search with a regex pattern.',
    'Average values in a fixed array.',
    'Write CSV lines with ofstream.',
    'Square via a lambda capture.',
    'Count unique entries in a set.',
    'Lookup by id in a map.',
    'Round-trip string and int via stoi.',
    'Join words with a delimiter into CSV.',
    'Show hex and decimal for a value.',
    'Display bits via bitset.',
    'Print an octal representation.',
    'Check all digits with all_of.',
    'Sort a vector in descending order.',
    'Generate a range with iota and multiply.',
    'Find min and max with minmax_element.',
    'Provide a fallback with optional.',
    'Test existence with filesystem.',
    'Compute hypotenuse from a struct point.',
  ],
  10: [
    'Print Hello World with printf.',
    'Compute a ratio from ints and doubles.',
    'Safely format a greeting with snprintf.',
    'Loop and printf each index.',
    'Sum a fixed int array with a loop.',
    'Open, read, and close a file safely.',
    'Guard division and log to stderr.',
    'Compute sqrt and pow with math.h.',
    'Define and init a struct Dog.',
    'Filter evens into a compact array.',
    'Print a key-value pair with strings.',
    'Format the current date with time.h.',
    'Compile and exec a regex, then free it.',
    'Average an int array with accumulation.',
    'Open a file for writing and fprintf.',
    'Define a simple square function.',
    'Count uniques by scanning sorted values.',
    'Define and print a struct Entry.',
    'Convert between string and int safely.',
    'Join words into CSV with strcat guards.',
    'Print hex and decimal together.',
    'Render bits with shifts and putchar.',
    'Print an octal formatting.',
    'Scan a code string for all digits.',
    'Sort with qsort and a comparator.',
    'Build a range and compute its product.',
    'Scan for min and max in one pass.',
    'Choose a user with a ternary null check.',
    'Check file existence with stat.',
    'Compute hypot from a struct point.',
  ],
};

function titleFor(section: number, idx: number): string {
  const curated = titlesBySection[section]?.[idx];
  if (curated) return curated;
  // fallback: ensure distinct + intent-based even for unexpected lengths
  return `Section ${section} - Lesson ${idx + 1}: Focus Drill`;
}

function descriptionFor(section: number, idx: number): string {
  const curated = descriptionsBySection[section]?.[idx];
  if (curated) return curated;
  const fallbackTitle = titleFor(section, idx);
  return `Practice ${fallbackTitle.toLowerCase()} with steady rhythm and clean accuracy.`;
}

export const makeLessons = (
  section: number,
  exerciseType: ExerciseType,
  difficulty: Difficulty,
  contents: string[],
  titles?: string[],
  descriptions?: string[]
) =>
  contents.map((content, idx) => ({
    section,
    exerciseType,
    difficulty,
    level: 100 * section + idx,
    order: idx + 1,
    title: titles?.[idx] ?? titleFor(section, idx),
    description: descriptions?.[idx] ?? descriptionFor(section, idx),
    keys: deriveKeys(content),
    targetFingers: [],
    unlockAfter: [],
    targetWpm: 20,
    minAccuracy: 90,
    content,
  }));
