import { Difficulty, ExerciseType } from '@prisma/client';

export const codingLessons = [
  // ============================================================================
  // SECTION 7: PYTHON (Levels 101-125)
  // ============================================================================
  {
    level: 101,
    order: 101,
    section: 7,
    title: 'Python: Hello, World!',
    description: 'Practice basic Python print syntax.',
    keys: ['p', 'r', 'i', 'n', 't', '(', ')', '"'],
    difficulty: Difficulty.BEGINNER,
    targetWpm: 30,
    minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [],
    content: 'print("Hello, World!")\nprint("Welcome to Python programming.")',
  },
  {
    level: 102,
    order: 102,
    section: 7,
    title: 'Python: Variables',
    description: 'Practice variable assignment and f-strings.',
    keys: ['=', 'f', '"', '{', '}'],
    difficulty: Difficulty.BEGINNER,
    targetWpm: 32,
    minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [101],
    content: 'name = "Alice"\nage = 30\nprint(f"Name: {name}, Age: {age}")',
  },
  {
    level: 103,
    order: 103,
    section: 7,
    title: 'Python: Lists',
    description: 'Practice Python list syntax with brackets and colons.',
    keys: ['[', ']', ':', ','],
    difficulty: Difficulty.BEGINNER,
    targetWpm: 35,
    minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [102],
    content:
      'numbers = [1, 2, 3, 4, 5]\nfruits = ["apple", "banana", "cherry"]\nprint(numbers[0])\nprint(fruits[1:])',
  },
  {
    level: 104,
    order: 104,
    section: 7,
    title: 'Python: For Loops',
    description: 'Practice `for` loops and the `in` keyword.',
    keys: ['f', 'o', 'r', 'i', 'n', ':'],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 38,
    minAccuracy: 96,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [103],
    content: 'for fruit in fruits:\n    print(fruit)\nfor i in range(5):\n    print(i * 2)',
  },
  {
    level: 105,
    order: 105,
    section: 7,
    title: 'Python: If/Elif/Else',
    description: 'Practice conditional logic with if, elif, and else.',
    keys: ['i', 'f', 'e', 'l', 's', ':', '>', '<', '='],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 40,
    minAccuracy: 96,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [104],
    isCheckpoint: true,
    content:
      'x = 10\nif x > 5:\n    print("x is greater than 5")\nelif x == 5:\n    print("x is 5")\nelse:\n    print("x is less than 5")',
  },
  {
    level: 106,
    order: 106,
    section: 7,
    title: 'Python: Functions (def)',
    description: 'Practice defining functions with `def`.',
    keys: ['d', 'e', 'f', '(', ')', ':', 'return'],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 42,
    minAccuracy: 96,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [105],
    content:
      'def greet(name):\n    return f"Hello, {name}!"\n\nmessage = greet("Bob")\nprint(message)',
  },
  {
    level: 107,
    order: 107,
    section: 7,
    title: 'Python: Dictionaries',
    description: 'Practice dictionary syntax with curly braces and colons.',
    keys: ['{', '}', ':', '"', ','],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 40,
    minAccuracy: 96,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [106],
    content:
      'person = {\n    "name": "John",\n    "age": 25,\n    "city": "New York"\n}\nprint(person["name"])',
  },
  {
    level: 108,
    order: 108,
    section: 7,
    title: 'Python: While Loops',
    description: 'Practice `while` loops and incrementing.',
    keys: ['w', 'h', 'i', 'l', 'e', ':', '<', '+', '='],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 42,
    minAccuracy: 96,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [107],
    content: 'count = 0\nwhile count < 5:\n    print(count)\n    count += 1',
  },
  {
    level: 109,
    order: 109,
    section: 7,
    title: 'Python: List Comprehensions',
    description: 'Practice list comprehensions.',
    keys: ['[', ']', 'f', 'o', 'r', 'i', 'n'],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 45,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [108],
    content:
      'squares = [x**2 for x in range(10)]\neven_numbers = [i for i in numbers if i % 2 == 0]',
  },
  {
    level: 110,
    order: 110,
    section: 7,
    title: 'Python: Dictionaries Checkpoint',
    description: 'Practice iterating over dictionaries.',
    keys: ['.', 'i', 't', 'e', 'm', 's', '(', ')'],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 46,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [109],
    isCheckpoint: true,
    content: 'for key, value in person.items():\n    print(f"{key}: {value}")',
  },
  {
    level: 111,
    order: 111,
    section: 7,
    title: 'Python: Imports',
    description: 'Practice import statements.',
    keys: ['i', 'm', 'p', 'o', 'r', 't', 'f', 's'],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 40,
    minAccuracy: 96,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [110],
    content: 'import math\nfrom datetime import datetime\n\nprint(math.pi)\nprint(datetime.now())',
  },
  {
    level: 112,
    order: 112,
    section: 7,
    title: 'Python: Classes (init)',
    description: 'Practice class definitions and __init__.',
    keys: [
      'c',
      'l',
      'a',
      's',
      'd',
      'e',
      'f',
      '_',
      'i',
      'n',
      't',
      '(',
      ')',
      ':',
      's',
      'e',
      'l',
      'f',
      '.',
    ],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 45,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [111],
    content:
      'class Dog:\n    def __init__(self, name, age):\n        self.name = name\n        self.age = age',
  },
  {
    level: 113,
    order: 113,
    section: 7,
    title: 'Python: Class Methods',
    description: 'Practice defining methods within a class.',
    keys: ['d', 'e', 'f', 's', 'e', 'l', 'f', '(', ')', ':', 'return'],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 46,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [112],
    content:
      'class Dog:\n    def __init__(self, name):\n        self.name = name\n\n    def bark(self):\n        return f"{self.name} says woof!"',
  },
  {
    level: 114,
    order: 114,
    section: 7,
    title: 'Python: Inheritance',
    description: 'Practice class inheritance.',
    keys: ['c', 'l', 'a', 's', '(', ')', ':', 's', 'u', 'p', 'e', 'r', '.'],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 48,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [113],
    content:
      'class Animal:\n    def __init__(self, name):\n        self.name = name\n\nclass Cat(Animal):\n    def __init__(self, name):\n        super().__init__(name)',
  },
  {
    level: 115,
    order: 115,
    section: 7,
    title: 'Python: Modules Checkpoint',
    description: 'Practice creating and using class instances.',
    keys: ['=', '(', ')', '.', 'p', 'r', 'i', 'n', 't'],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 50,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [114],
    isCheckpoint: true,
    content: 'my_dog = Dog("Rex", 5)\nprint(my_dog.name)\nprint(my_dog.age)',
  },
  {
    level: 116,
    order: 116,
    section: 7,
    title: 'Python: File Handling (Read)',
    description: 'Practice reading from files using `with open`.',
    keys: ['w', 'i', 't', 'h', 'o', 'p', 'e', 'n', '(', ')', 'a', 's', ':', '.', 'r', 'd'],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 47,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [115],
    content: 'with open("file.txt", "r") as f:\n    content = f.read()\n    print(content)',
  },
  {
    level: 117,
    order: 117,
    section: 7,
    title: 'Python: File Handling (Write)',
    description: 'Practice writing to files using `with open`.',
    keys: ['w', 'i', 't', 'h', 'o', 'p', 'e', 'n', '(', ')', 'a', 's', ':', '.', 'f', 'r'],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 47,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [116],
    content:
      'with open("output.txt", "w") as f:\n    f.write("This is a new line.")\n    f.write("Hello from Python.")',
  },
  {
    level: 118,
    order: 118,
    section: 7,
    title: 'Python: Try/Except',
    description: 'Practice error handling with try/except.',
    keys: ['t', 'r', 'y', ':', 'e', 'x', 'c', 'p', 'Z', 'o', 'D', 'v', 'i', 's', 'n', 'E', 'a'],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 48,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [117],
    content: 'try:\n    result = 10 / 0\nexcept ZeroDivisionError as e:\n    print(f"Error: {e}")',
  },
  {
    level: 119,
    order: 119,
    section: 7,
    title: 'Python: Lambda Functions',
    description: 'Practice simple lambda functions.',
    keys: ['l', 'a', 'm', 'b', 'd', ':', 'x', '+', 'y'],
    difficulty: Difficulty.EXPERT,
    targetWpm: 50,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [118],
    content:
      'add = lambda x, y: x + y\nprint(add(5, 3))\ndoubled = (lambda x: x * 2)(10)\nprint(doubled)',
  },
  {
    level: 120,
    order: 120,
    section: 7,
    title: 'Python: Map and Filter',
    description: 'Practice using map and filter with lambda.',
    keys: ['m', 'a', 'p', 'f', 'i', 'l', 't', 'e', 'r', 'l', 's', '(', ')'],
    difficulty: Difficulty.EXPERT,
    targetWpm: 52,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [119],
    isCheckpoint: true,
    content:
      'numbers = [1, 2, 3, 4, 5]\nsquares = list(map(lambda x: x**2, numbers))\nevens = list(filter(lambda x: x % 2 == 0, numbers))',
  },
  {
    level: 121,
    order: 121,
    section: 7,
    title: 'Python: Tuples',
    description: 'Practice tuple creation and unpacking.',
    keys: ['(', ')', ',', '=', 'x', 'y', 'z'],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 45,
    minAccuracy: 96,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [120],
    content: 'point = (10, 20, 30)\nx, y, z = point\nprint(f"x: {x}, y: {y}")',
  },
  {
    level: 122,
    order: 122,
    section: 7,
    title: 'Python: Sets',
    description: 'Practice set creation and operations.',
    keys: ['{', '}', 's', 'e', 't', '(', ')', '.', 'a', 'd', 'r', 'm', 'o', 'v'],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 48,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [121],
    content: 'my_set = {1, 2, 3, 3, 4}\nmy_set.add(5)\nmy_set.remove(1)\nprint(my_set)',
  },
  {
    level: 123,
    order: 123,
    section: 7,
    title: 'Python: String Methods',
    description: 'Practice common string methods.',
    keys: ['.', 'u', 'p', 'e', 'r', 'l', 'o', 'w', 's', 't', 'i', '(', ')', 'p', 'j'],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 50,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [122],
    content:
      'text = "Hello Python"\nprint(text.upper())\nprint(text.lower())\nprint(text.replace("Python", "World"))',
  },
  {
    level: 124,
    order: 124,
    section: 7,
    title: 'Python: JSON Handling',
    description: 'Practice loading and dumping JSON.',
    keys: ['i', 'm', 'p', 'o', 'r', 't', 'j', 's', 'n', '.', 'l', 'd', 'u', '(', ')'],
    difficulty: Difficulty.EXPERT,
    targetWpm: 52,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [123],
    content:
      'import json\n\ndata = {"name": "Test", "value": 123}\njson_string = json.dumps(data)\nparsed_data = json.loads(json_string)',
  },
  {
    level: 125,
    order: 125,
    section: 7,
    title: 'Python: Final Checkpoint',
    description: 'Combine classes, methods, and comprehensions.',
    keys: ['c', 'l', 'a', 's', 'd', 'e', 'f', '_', 'i', 'n', 't', 'g', 'o', 'p', 'v'],
    difficulty: Difficulty.EXPERT,
    targetWpm: 55,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [124],
    isCheckpoint: true,
    content:
      'class DataHandler:\n    def __init__(self, data_list):\n        self.data = data_list\n\n    def get_positives(self):\n        return [x for x in self.data if x > 0]',
  },

  // ============================================================================
  // SECTION 8: JAVA (Levels 126-150)
  // ============================================================================
  {
    level: 126,
    order: 126,
    section: 8,
    title: 'Java: Hello, World!',
    description: 'Practice basic Java class and main method syntax.',
    keys: [
      'p',
      'u',
      'b',
      'l',
      'i',
      'c',
      's',
      't',
      'a',
      'v',
      'o',
      'd',
      'm',
      'n',
      'S',
      'y',
      'r',
      'g',
      '(',
      ')',
      '{',
      '}',
      ';',
      '.',
    ],
    difficulty: Difficulty.BEGINNER,
    targetWpm: 30,
    minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [125],
    content:
      'public class Main {\n    public static void main(String[] args) {\n        System.out.println("Hello, World!");\n    }\n}',
  },
  {
    level: 127,
    order: 127,
    section: 8,
    title: 'Java: Variables and Types',
    description: 'Practice Java variable declarations with types.',
    keys: ['i', 'n', 't', 'S', 'r', 'g', 'd', 'o', 'u', 'b', 'l', 'e', '=', ';', '+', '.'],
    difficulty: Difficulty.BEGINNER,
    targetWpm: 32,
    minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [126],
    content:
      'int age = 25;\nString name = "Java";\ndouble pi = 3.14;\nSystem.out.println(name + " is " + age);',
  },
  {
    level: 128,
    order: 128,
    section: 8,
    title: 'Java: For Loops',
    description: 'Practice Java `for` loop syntax.',
    keys: ['f', 'o', 'r', '(', ';', ')', '{', '}', 'i', 'n', 't', '<', '+', '='],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 35,
    minAccuracy: 96,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [127],
    content: 'for (int i = 0; i < 5; i++) {\n    System.out.println(i);\n}',
  },
  {
    level: 129,
    order: 129,
    section: 8,
    title: 'Java: If/Else',
    description: 'Practice Java conditional logic.',
    keys: ['i', 'f', 'e', 'l', 's', '(', ')', '{', '}', '>', '=', '.'],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 38,
    minAccuracy: 96,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [128],
    content:
      'int x = 10;\nif (x > 5) {\n    System.out.println("x is greater than 5");\n} else {\n    System.out.println("x is not greater than 5");\n}',
  },
  {
    level: 130,
    order: 130,
    section: 8,
    title: 'Java: Arrays',
    description: 'Practice Java array initialization and access.',
    keys: ['i', 'n', 't', '[', ']', '{', '}', ',', ';', '=', 'S', 'r', 'g', 'w', '.'],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 40,
    minAccuracy: 96,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [129],
    isCheckpoint: true,
    content:
      'int[] numbers = {1, 2, 3, 4, 5};\nString[] names = new String[3];\nnames[0] = "Alice";\nSystem.out.println(numbers[2]);',
  },
  {
    level: 131,
    order: 131,
    section: 8,
    title: 'Java: Methods',
    description: 'Practice defining and calling static methods.',
    keys: [
      'p',
      'u',
      'b',
      'l',
      'i',
      'c',
      's',
      't',
      'a',
      'v',
      'o',
      'd',
      'i',
      'n',
      '(',
      ')',
      '{',
      '}',
      ';',
      'r',
      'e',
    ],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 42,
    minAccuracy: 96,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [130],
    content:
      'public class MathUtils {\n    public static int add(int a, int b) {\n        return a + b;\n    }\n    int sum = add(5, 3);\n}',
  },
  {
    level: 132,
    order: 132,
    section: 8,
    title: 'Java: Classes (Constructor)',
    description: 'Practice class definitions and constructors.',
    keys: [
      'p',
      'u',
      'b',
      'l',
      'i',
      'c',
      'c',
      'l',
      'a',
      's',
      'S',
      'r',
      'g',
      '(',
      ')',
      '{',
      '}',
      ';',
      't',
      'h',
      '.',
      '=',
    ],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 45,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [131],
    content:
      'public class Car {\n    String model;\n    public Car(String model) {\n        this.model = model;\n    }\n}',
  },
  {
    level: 133,
    order: 133,
    section: 8,
    title: 'Java: Class Methods',
    description: 'Practice defining methods within a class.',
    keys: [
      'p',
      'u',
      'b',
      'l',
      'i',
      'c',
      'v',
      'o',
      'd',
      '(',
      ')',
      '{',
      '}',
      'S',
      'y',
      's',
      't',
      'e',
      'm',
      '.',
      'o',
      'u',
      'r',
      'n',
    ],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 46,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [132],
    content:
      'public class Car {\n    public void startEngine() {\n        System.out.println("Engine started!");\n    }\n}',
  },
  {
    level: 134,
    order: 134,
    section: 8,
    title: 'Java: Creating Objects',
    description: 'Practice instantiating objects with `new`.',
    keys: ['C', 'a', 'r', 'm', 'y', '=', 'n', 'e', 'w', '(', ')', ';', '.', 's', 't'],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 47,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [133],
    content: 'Car myCar = new Car("Tesla");\nmyCar.startEngine();',
  },
  {
    level: 135,
    order: 135,
    section: 8,
    title: 'Java: ArrayList (Import)',
    description: 'Practice importing and creating ArrayLists.',
    keys: [
      'i',
      'm',
      'p',
      'o',
      'r',
      't',
      'j',
      'a',
      'v',
      '.',
      'u',
      'l',
      'A',
      'y',
      'L',
      's',
      '<',
      '>',
      '(',
      ')',
      ';',
      'n',
      'e',
      'w',
    ],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 48,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [134],
    isCheckpoint: true,
    content:
      'import java.util.ArrayList;\n\nArrayList<String> names = new ArrayList<String>();\nnames.add("Alice");\nnames.add("Bob");',
  },
  {
    level: 136,
    order: 136,
    section: 8,
    title: 'Java: ArrayList (Methods)',
    description: 'Practice common ArrayList methods.',
    keys: ['.', 'a', 'd', 'g', 'e', 't', '(', ')', 's', 'i', 'z', 'r', 'm', 'o', 'v'],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 50,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [135],
    content:
      'names.add("Charlie");\nString first = names.get(0);\nint count = names.size();\nnames.remove(1);',
  },
  {
    level: 137,
    order: 137,
    section: 8,
    title: 'Java: Enhanced For Loop',
    description: 'Practice iterating with the enhanced for loop.',
    keys: ['f', 'o', 'r', '(', 'S', 't', 'r', 'i', 'n', 'g', ':', ')', '{', '}', 'y', 's', '.'],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 45,
    minAccuracy: 96,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [136],
    content: 'for (String name : names) {\n    System.out.println(name);\n}',
  },
  {
    level: 138,
    order: 138,
    section: 8,
    title: 'Java: HashMap',
    description: 'Practice importing and using HashMaps.',
    keys: [
      'i',
      'm',
      'p',
      'o',
      'r',
      't',
      'j',
      'a',
      'v',
      '.',
      'u',
      'l',
      'H',
      's',
      'M',
      '<',
      '>',
      '(',
      ')',
      ';',
      'n',
      'e',
      'w',
    ],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 50,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [137],
    content:
      'import java.util.HashMap;\n\nHashMap<String, Integer> scores = new HashMap<String, Integer>();\nscores.put("Alice", 100);',
  },
  {
    level: 139,
    order: 139,
    section: 8,
    title: 'Java: HashMap (Methods)',
    description: 'Practice HashMap put, get, and remove.',
    keys: ['.', 'p', 'u', 't', 'g', 'e', '(', ')', 'r', 'm', 'o', 'v', 'S', 'I', 'n'],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 52,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [138],
    content: 'scores.put("Bob", 90);\nint aliceScore = scores.get("Alice");\nscores.remove("Bob");',
  },
  {
    level: 140,
    order: 140,
    section: 8,
    title: 'Java: Collections Checkpoint',
    description: 'Practice iterating over a HashMap.',
    keys: [
      'f',
      'o',
      'r',
      '(',
      'S',
      't',
      'r',
      'i',
      'n',
      'g',
      ':',
      ')',
      '{',
      '}',
      '.',
      'k',
      'E',
      'y',
      'e',
    ],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 53,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [139],
    isCheckpoint: true,
    content:
      'for (String name : scores.keySet()) {\n    System.out.println(name + ": " + scores.get(name));\n}',
  },
  {
    level: 141,
    order: 141,
    section: 8,
    title: 'Java: Inheritance',
    description: 'Practice `extends` keyword.',
    keys: [
      'p',
      'u',
      'b',
      'l',
      'i',
      'c',
      'c',
      'l',
      'a',
      's',
      'e',
      'x',
      't',
      'n',
      'd',
      '(',
      ')',
      '{',
      '}',
    ],
    difficulty: Difficulty.EXPERT,
    targetWpm: 50,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [140],
    content:
      'public class Animal {\n    public void makeSound() {\n        System.out.println("...sound...");\n    }\n}\n\npublic class Dog extends Animal {\n}',
  },
  {
    level: 142,
    order: 142,
    section: 8,
    title: 'Java: Super Constructor',
    description: 'Practice calling `super()` in a constructor.',
    keys: ['s', 'u', 'p', 'e', 'r', '(', ')', ';', 't', 'h', 'i', '.', '='],
    difficulty: Difficulty.EXPERT,
    targetWpm: 52,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [141],
    content:
      'public class Dog extends Animal {\n    String name;\n    public Dog(String name) {\n        super();\n        this.name = name;\n    }\n}',
  },
  {
    level: 143,
    order: 143,
    section: 8,
    title: 'Java: Overriding Methods',
    description: 'Practice `@Override` annotation.',
    keys: [
      '@',
      'O',
      'v',
      'e',
      'r',
      'i',
      'd',
      'p',
      'u',
      'b',
      'l',
      'c',
      'v',
      'o',
      '(',
      ')',
      '{',
      '}',
      'S',
      'y',
      's',
      't',
      'm',
      '.',
      'n',
    ],
    difficulty: Difficulty.EXPERT,
    targetWpm: 54,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [142],
    content: '@Override\npublic void makeSound() {\n    System.out.println("Woof!");\n}',
  },
  {
    level: 144,
    order: 144,
    section: 8,
    title: 'Java: Interfaces',
    description: 'Practice defining an interface.',
    keys: [
      'p',
      'u',
      'b',
      'l',
      'i',
      'c',
      'i',
      'n',
      't',
      'e',
      'r',
      'f',
      'a',
      'c',
      'v',
      'o',
      'd',
      '(',
      ')',
      ';',
    ],
    difficulty: Difficulty.EXPERT,
    targetWpm: 50,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [143],
    content: 'public interface Drivable {\n    void drive();\n    void stop();\n}',
  },
  {
    level: 145,
    order: 145,
    section: 8,
    title: 'Java: Implementing Interfaces',
    description: 'Practice `implements` keyword.',
    keys: [
      'p',
      'u',
      'b',
      'l',
      'i',
      'c',
      'c',
      'l',
      'a',
      's',
      'm',
      'e',
      'n',
      't',
      'D',
      'r',
      'v',
      'b',
      '(',
      ')',
      '{',
      '}',
      '@',
      'O',
    ],
    difficulty: Difficulty.EXPERT,
    targetWpm: 53,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [144],
    isCheckpoint: true,
    content:
      'public class Vehicle implements Drivable {\n    @Override\n    public void drive() {\n        System.out.println("Vehicle is driving.");\n    }\n    @Override\n    public void stop() {\n        System.out.println("Vehicle stopped.");\n    }\n}',
  },
  {
    level: 146,
    order: 146,
    section: 8,
    title: 'Java: Try/Catch',
    description: 'Practice basic try/catch blocks.',
    keys: [
      't',
      'r',
      'y',
      '{',
      '}',
      'c',
      'a',
      'h',
      '(',
      'E',
      'x',
      'e',
      'p',
      'i',
      'o',
      'n',
      ')',
      'e',
      '.',
      'g',
    ],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 50,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [145],
    content:
      'try {\n    int result = 10 / 0;\n} catch (Exception e) {\n    System.out.println("An error occurred: " + e.getMessage());\n}',
  },
  {
    level: 147,
    order: 147,
    section: 8,
    title: 'Java: Try/Catch/Finally',
    description: 'Practice adding a `finally` block.',
    keys: ['t', 'r', 'y', 'c', 'a', 'h', 'f', 'i', 'n', 'l', '{', '}', '(', ')', '.'],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 52,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [146],
    content:
      'try {\n    // code\n} catch (Exception e) {\n    // error handling\n} finally {\n    System.out.println("This always runs.");\n}',
  },
  {
    level: 148,
    order: 148,
    section: 8,
    title: 'Java: String Methods',
    description: 'Practice common String class methods.',
    keys: [
      '.',
      'l',
      'e',
      'n',
      'g',
      't',
      'h',
      '(',
      ')',
      'c',
      'A',
      'r',
      's',
      'u',
      'b',
      'i',
      'q',
      'o',
    ],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 48,
    minAccuracy: 96,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [147],
    content:
      'String s = "Hello Java";\nint len = s.length();\nchar c = s.charAt(1);\nString sub = s.substring(6);\nboolean eq = s.equals("Test");',
  },
  {
    level: 149,
    order: 149,
    section: 8,
    title: 'Java: Static Keyword',
    description: 'Practice `static` variables and methods.',
    keys: [
      'p',
      'u',
      'b',
      'l',
      'i',
      'c',
      's',
      't',
      'a',
      'c',
      'i',
      'n',
      'v',
      'o',
      'd',
      '(',
      ')',
      '{',
      '}',
      ';',
      '=',
    ],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 53,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [148],
    content:
      'public class Counter {\n    public static int count = 0;\n    public static void increment() {\n        count++;\n    }\n}',
  },
  {
    level: 150,
    order: 150,
    section: 8,
    title: 'Java: Final Checkpoint',
    description: 'Practice ArrayLists and method calls.',
    keys: [
      'A',
      'r',
      'y',
      'L',
      'i',
      's',
      't',
      '<',
      '>',
      '(',
      ')',
      '.',
      'n',
      'e',
      'w',
      'a',
      'd',
      'g',
      'S',
      'm',
      'p',
      'o',
      'v',
    ],
    difficulty: Difficulty.EXPERT,
    targetWpm: 55,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [149],
    isCheckpoint: true,
    content:
      'import java.util.ArrayList;\n\npublic class Test {\n    public static void main(String[] args) {\n        ArrayList<String> list = new ArrayList<String>();\n        list.add("Java");\n        list.add("Python");\n        System.out.println(list.get(0));\n    }\n}',
  },

  // ============================================================================
  // SECTION 9: C++ (Levels 151-175)
  // ============================================================================
  {
    level: 151,
    order: 151,
    section: 9,
    title: 'C++: Hello, World!',
    description: 'Practice basic C++ iostream syntax.',
    keys: [
      '#',
      'i',
      'n',
      'c',
      'l',
      'u',
      'd',
      'e',
      '<',
      '>',
      's',
      't',
      'm',
      ':',
      'o',
      '(',
      ')',
      '{',
      '}',
      ';',
    ],
    difficulty: Difficulty.BEGINNER,
    targetWpm: 30,
    minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [150],
    content:
      '#include <iostream>\n\nint main() {\n    std::cout << "Hello, World!" << std::endl;\n    return 0;\n}',
  },
  {
    level: 152,
    order: 152,
    section: 9,
    title: 'C++: Variables and Types',
    description: 'Practice C++ variable declarations.',
    keys: [
      'i',
      'n',
      't',
      'd',
      'o',
      'u',
      'b',
      'l',
      'e',
      'c',
      'h',
      'a',
      'r',
      's',
      'g',
      ';',
      '=',
      ':',
      '"',
    ],
    difficulty: Difficulty.BEGINNER,
    targetWpm: 32,
    minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [151],
    content:
      'int age = 30;\ndouble price = 19.99;\nchar initial = \'J\';\nstd::string name = "Bjarne";',
  },
  {
    level: 153,
    order: 153,
    section: 9,
    title: 'C++: For Loops',
    description: 'Practice C++ `for` loop syntax.',
    keys: ['f', 'o', 'r', '(', ';', ')', '{', '}', 'i', 'n', 't', '<', '+', '=', ':', '<', 'l'],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 35,
    minAccuracy: 96,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [152],
    content: 'for (int i = 0; i < 5; ++i) {\n    std::cout << i << std::endl;\n}',
  },
  {
    level: 154,
    order: 154,
    section: 9,
    title: 'C++: If/Else',
    description: 'Practice C++ conditional logic.',
    keys: ['i', 'f', 'e', 'l', 's', '(', ')', '{', '}', '>', '=', ':', '<', '"'],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 38,
    minAccuracy: 96,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [153],
    content:
      'int x = 10;\nif (x > 5) {\n    std::cout << "x is greater than 5";\n} else {\n    std::cout << "x is not greater than 5";\n}',
  },
  {
    level: 155,
    order: 155,
    section: 9,
    title: 'C++: Vectors',
    description: 'Practice std::vector initialization and access.',
    keys: [
      '#',
      'i',
      'n',
      'c',
      'l',
      'u',
      'd',
      'e',
      '<',
      'v',
      'e',
      'c',
      't',
      'o',
      'r',
      '>',
      's',
      'd',
      ':',
      '{',
      '}',
      ';',
      'g',
      'p',
      'h',
      'b',
      'k',
    ],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 40,
    minAccuracy: 96,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [154],
    isCheckpoint: true,
    content:
      '#include <vector>\n\nstd::vector<int> numbers = {1, 2, 3, 4, 5};\nstd::vector<std::string> words;\nwords.push_back("C++");',
  },
  {
    level: 156,
    order: 156,
    section: 9,
    title: 'C++: Vector Iteration',
    description: 'Practice iterating over a std::vector.',
    keys: ['f', 'o', 'r', '(', 'a', 'u', 't', ':', ')', '{', '}', 's', 'd', 'c', 'l', '<', 'n'],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 42,
    minAccuracy: 96,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [155],
    content: 'for (auto const& num : numbers) {\n    std::cout << num << std::endl;\n}',
  },
  {
    level: 157,
    order: 157,
    section: 9,
    title: 'C++: Functions',
    description: 'Practice defining and calling functions.',
    keys: [
      'i',
      'n',
      't',
      'a',
      'd',
      '(',
      ')',
      '{',
      '}',
      'r',
      'e',
      'u',
      ';',
      's',
      'm',
      'c',
      'o',
      'l',
    ],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 40,
    minAccuracy: 96,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [156],
    content:
      'int add(int a, int b) {\n    return a + b;\n}\n\nint sum = add(5, 3);\nstd::cout << sum << std::endl;',
  },
  {
    level: 158,
    order: 158,
    section: 9,
    title: 'C++: Classes (Header)',
    description: 'Practice a simple class declaration in a header.',
    keys: [
      'c',
      'l',
      'a',
      's',
      '{',
      '}',
      ';',
      'p',
      'u',
      'b',
      'i',
      'v',
      't',
      'e',
      ':',
      'n',
      '(',
      ')',
      'o',
      'd',
    ],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 45,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [157],
    content:
      'class Rectangle {\npublic:\n    Rectangle(int w, int h);\n    int getArea();\nprivate:\n    int width, height;\n};',
  },
  {
    level: 159,
    order: 159,
    section: 9,
    title: 'C++: Classes (Implementation)',
    description: 'Practice implementing class methods.',
    keys: [
      'R',
      'e',
      'c',
      't',
      'a',
      'n',
      'g',
      'l',
      ':',
      '(',
      ')',
      '{',
      '}',
      'w',
      'i',
      'd',
      'h',
      '=',
      ';',
      'r',
      'u',
      '*',
    ],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 48,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [158],
    content:
      'Rectangle::Rectangle(int w, int h) {\n    width = w;\n    height = h;\n}\n\nint Rectangle::getArea() {\n    return width * height;\n}',
  },
  {
    level: 160,
    order: 160,
    section: 9,
    title: 'C++: Class Checkpoint',
    description: 'Practice creating and using class instances.',
    keys: [
      '#',
      'i',
      'n',
      'c',
      'l',
      'u',
      'd',
      'e',
      '"',
      '.',
      'h',
      '>',
      'm',
      'a',
      '(',
      ')',
      '{',
      '}',
      'R',
      't',
      'g',
      'r',
      'e',
      '5',
      '0',
      ';',
    ],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 50,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [159],
    isCheckpoint: true,
    content:
      '#include "Rectangle.h"\n\nint main() {\n    Rectangle rect(10, 5);\n    std::cout << rect.getArea() << std::endl;\n    return 0;\n}',
  },
  {
    level: 161,
    order: 161,
    section: 9,
    title: 'C++: Pointers',
    description: 'Practice pointer declaration and dereferencing.',
    keys: [
      'i',
      'n',
      't',
      'v',
      'a',
      'l',
      '=',
      ';',
      '*',
      'p',
      'r',
      '&',
      's',
      'd',
      'c',
      'o',
      'u',
      '<',
      ':',
      'l',
    ],
    difficulty: Difficulty.EXPERT,
    targetWpm: 48,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [160],
    content: 'int val = 10;\nint *ptr = &val;\n\nstd::cout << "Value: " << *ptr << std::endl;',
  },
  {
    level: 162,
    order: 162,
    section: 9,
    title: 'C++: References',
    description: 'Practice using references.',
    keys: [
      'i',
      'n',
      't',
      'v',
      'a',
      'l',
      '=',
      ';',
      '&',
      'r',
      'e',
      'f',
      's',
      'd',
      'c',
      'o',
      'u',
      '<',
      ':',
      'l',
    ],
    difficulty: Difficulty.EXPERT,
    targetWpm: 47,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [161],
    content:
      'int val = 20;\nint &ref = val;\nref = 30;\nstd::cout << "Value: " << val << std::endl;',
  },
  {
    level: 163,
    order: 163,
    section: 9,
    title: 'C++: Pointers in Functions',
    description: 'Practice passing pointers to functions.',
    keys: ['v', 'o', 'i', 'd', 'n', 'c', 'r', 'm', '(', 't', '*', 'p', ')', '{', '}', ';'],
    difficulty: Difficulty.EXPERT,
    targetWpm: 50,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [162],
    content:
      'void increment(int *p) {\n    (*p)++;\n}\n\nint x = 5;\nincrement(&x);\nstd::cout << x << std::endl;',
  },
  {
    level: 164,
    order: 164,
    section: 9,
    title: 'C++: New and Delete',
    description: 'Practice dynamic memory allocation.',
    keys: ['i', 'n', 't', '*', 'p', '=', 'w', ';', 'd', 'l', 'e', '[', ']'],
    difficulty: Difficulty.EXPERT,
    targetWpm: 52,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [163],
    content: 'int *p = new int;\n*p = 100;\ndelete p;\n\nint *arr = new int[5];\ndelete[] arr;',
  },
  {
    level: 165,
    order: 165,
    section: 9,
    title: 'C++: Pointers Checkpoint',
    description: 'Practice allocating an object with `new`.',
    keys: [
      'R',
      'e',
      'c',
      't',
      'a',
      'n',
      'g',
      'l',
      '*',
      'p',
      '=',
      'w',
      '(',
      ')',
      ';',
      'd',
      's',
      'o',
      'u',
      '<',
      ':',
      '->',
      'A',
    ],
    difficulty: Difficulty.EXPERT,
    targetWpm: 53,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [164],
    isCheckpoint: true,
    content:
      'Rectangle *pRect = new Rectangle(7, 3);\nstd::cout << "Area: " << pRect->getArea() << std::endl;\ndelete pRect;',
  },
  {
    level: 166,
    order: 166,
    section: 9,
    title: 'C++: Maps',
    description: 'Practice std::map initialization and insertion.',
    keys: [
      '#',
      'i',
      'n',
      'c',
      'l',
      'u',
      'd',
      'e',
      '<',
      'm',
      'a',
      'p',
      '>',
      's',
      't',
      'd',
      ':',
      'g',
      'I',
      'r',
      'o',
      '[',
      ']',
      '=',
      ';',
    ],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 48,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [165],
    content:
      '#include <map>\n\nstd::map<std::string, int> scores;\nscores["Alice"] = 100;\nscores["Bob"] = 90;',
  },
  {
    level: 167,
    order: 167,
    section: 9,
    title: 'C++: Map Iteration',
    description: 'Practice iterating over a std::map.',
    keys: [
      'f',
      'o',
      'r',
      '(',
      'a',
      'u',
      't',
      'c',
      'n',
      's',
      '&',
      ':',
      ')',
      '{',
      '}',
      'p',
      'i',
      '.',
      'd',
      '<',
      'l',
      'e',
    ],
    difficulty: Difficulty.EXPERT,
    targetWpm: 52,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [166],
    content:
      'for (auto const& [name, score] : scores) {\n    std::cout << name << ": " << score << std::endl;\n}',
  },
  {
    level: 168,
    order: 168,
    section: 9,
    title: 'C++: Inheritance',
    description: 'Practice public inheritance syntax.',
    keys: [
      'c',
      'l',
      'a',
      's',
      'D',
      'o',
      'g',
      ':',
      'p',
      'u',
      'b',
      'i',
      'A',
      'n',
      'm',
      '{',
      '}',
      ';',
    ],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 46,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [167],
    content:
      'class Animal {\npublic:\n    void eat() { std::cout << "Eating..." << std::endl; }\n};\n\nclass Dog : public Animal {\n};',
  },
  {
    level: 169,
    order: 169,
    section: 9,
    title: 'C++: Virtual Functions',
    description: 'Practice `virtual` and `override` keywords.',
    keys: [
      'v',
      'i',
      'r',
      't',
      'u',
      'a',
      'l',
      'o',
      'd',
      's',
      'p',
      'e',
      'k',
      '(',
      ')',
      '{',
      '}',
      ';',
      'n',
      'c',
      'g',
      'v',
    ],
    difficulty: Difficulty.EXPERT,
    targetWpm: 53,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [168],
    content:
      'class Animal {\npublic:\n    virtual void speak() { std::cout << "..." << std::endl; }\n};\n\nclass Dog : public Animal {\npublic:\n    void speak() override { std::cout << "Woof!" << std::endl; }\n};',
  },
  {
    level: 170,
    order: 170,
    section: 9,
    title: 'C++: Polymorphism Checkpoint',
    description: 'Practice polymorphism with pointers.',
    keys: [
      'A',
      'n',
      'i',
      'm',
      'a',
      'l',
      '*',
      'p',
      '=',
      'w',
      'D',
      'o',
      'g',
      '(',
      ')',
      ';',
      's',
      'e',
      'k',
      'd',
      'l',
      't',
      '->',
    ],
    difficulty: Difficulty.EXPERT,
    targetWpm: 55,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [169],
    isCheckpoint: true,
    content: 'Animal *pAnimal = new Dog();\npAnimal->speak();\ndelete pAnimal;',
  },
  {
    level: 171,
    order: 171,
    section: 9,
    title: 'C++: File I/O (Write)',
    description: 'Practice writing to files with `ofstream`.',
    keys: [
      '#',
      'i',
      'n',
      'c',
      'l',
      'u',
      'd',
      'e',
      '<',
      'f',
      's',
      't',
      'r',
      'e',
      'a',
      'm',
      '>',
      'o',
      '(',
      ')',
      ';',
      '<',
      '"',
      'H',
      'l',
      'o',
      'W',
      'd',
      'p',
      '.',
    ],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 50,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [170],
    content:
      '#include <fstream>\n\nstd::ofstream outFile("output.txt");\noutFile << "Hello, World!" << std::endl;\noutFile.close();',
  },
  {
    level: 172,
    order: 172,
    section: 9,
    title: 'C++: File I/O (Read)',
    description: 'Practice reading from files with `ifstream`.',
    keys: [
      '#',
      'i',
      'n',
      'c',
      'l',
      'u',
      'd',
      'e',
      '<',
      'f',
      's',
      't',
      'r',
      'e',
      'a',
      'm',
      '>',
      'i',
      '(',
      ')',
      ';',
      'g',
      'l',
      'w',
      'h',
      'o',
      'u',
      'd',
      ':',
      'p',
      '.',
    ],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 52,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [171],
    content:
      '#include <fstream>\n#include <string>\n\nstd::ifstream inFile("input.txt");\nstd::string line;\nwhile (std::getline(inFile, line)) {\n    std::cout << line << std::endl;\n}\ninFile.close();',
  },
  {
    level: 173,
    order: 173,
    section: 9,
    title: 'C++: Templates',
    description: 'Practice function templates.',
    keys: [
      't',
      'e',
      'm',
      'p',
      'l',
      'a',
      '<',
      'c',
      's',
      'T',
      '>',
      '(',
      ')',
      '{',
      '}',
      'i',
      'n',
      'r',
      'u',
      'b',
      'd',
      'o',
    ],
    difficulty: Difficulty.EXPERT,
    targetWpm: 50,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [172],
    content:
      'template <class T>\nT add(T a, T b) {\n    return a + b;\n}\n\nint int_sum = add<int>(3, 4);\ndouble double_sum = add<double>(1.5, 2.5);',
  },
  {
    level: 174,
    order: 174,
    section: 9,
    title: 'C++: Structs',
    description: 'Practice simple struct definitions.',
    keys: [
      's',
      't',
      'r',
      'u',
      'c',
      'P',
      'o',
      'i',
      'n',
      '{',
      '}',
      ';',
      'd',
      'b',
      'l',
      'e',
      'x',
      'y',
      'p',
      '.',
      '=',
    ],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 45,
    minAccuracy: 96,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [173],
    content:
      'struct Point {\n    double x;\n    double y;\n};\n\nPoint p1;\np1.x = 10.0;\np1.y = 20.0;',
  },
  {
    level: 175,
    order: 175,
    section: 9,
    title: 'C++: Final Checkpoint',
    description: 'Practice classes, headers, and methods.',
    keys: [
      'c',
      'l',
      'a',
      's',
      'p',
      'u',
      'b',
      'i',
      'v',
      't',
      'e',
      ':',
      'h',
      'd',
      'r',
      '(',
      ')',
      '{',
      '}',
      ';',
      'n',
      'w',
      'g',
      '*',
    ],
    difficulty: Difficulty.EXPERT,
    targetWpm: 55,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [174],
    isCheckpoint: true,
    content:
      '#include "Rectangle.h"\n\nRectangle::Rectangle(int w, int h) {\n    width = w;\n    height = h;\n}\n\nint Rectangle::getArea() {\n    return width * height;\n}',
  },

  // ============================================================================
  // SECTION 10: C (Levels 176-200)
  // ============================================================================
  {
    level: 176,
    order: 176,
    section: 10,
    title: 'C: Hello, World!',
    description: 'Practice basic C stdio.h syntax.',
    keys: [
      '#',
      'i',
      'n',
      'c',
      'l',
      'u',
      'd',
      'e',
      '<',
      's',
      't',
      'o',
      'h',
      '>',
      'p',
      'r',
      'f',
      '(',
      ')',
      '{',
      '}',
      ';',
      'm',
      'a',
      'v',
      'W',
      'l',
      'd',
      '\\',
      '0',
    ],
    difficulty: Difficulty.BEGINNER,
    targetWpm: 30,
    minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [175],
    content:
      '#include <stdio.h>\n\nint main() {\n    printf("Hello, World!\\n");\n    return 0;\n}',
  },
  {
    level: 177,
    order: 177,
    section: 10,
    title: 'C: Variables and Types',
    description: 'Practice C variable declarations.',
    keys: [
      'i',
      'n',
      't',
      'f',
      'l',
      'o',
      'a',
      'c',
      'h',
      'r',
      ';',
      '=',
      'p',
      '(',
      ')',
      '%',
      'd',
      'c',
      '\\',
      'g',
      'D',
    ],
    difficulty: Difficulty.BEGINNER,
    targetWpm: 32,
    minAccuracy: 95,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [176],
    content:
      'int age = 30;\nfloat pi = 3.14f;\nchar initial = \'D\';\nprintf("Age: %d\\n", age);\nprintf("Initial: %c\\n", initial);',
  },
  {
    level: 178,
    order: 178,
    section: 10,
    title: 'C: For Loops',
    description: 'Practice C `for` loop syntax.',
    keys: [
      'f',
      'o',
      'r',
      '(',
      ';',
      ')',
      '{',
      '}',
      'i',
      'n',
      't',
      '<',
      '+',
      '=',
      'p',
      '%',
      'd',
      '\\',
    ],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 35,
    minAccuracy: 96,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [177],
    content: 'for (int i = 0; i < 5; i++) {\n    printf("%d\\n", i);\n}',
  },
  {
    level: 179,
    order: 179,
    section: 10,
    title: 'C: If/Else',
    description: 'Practice C conditional logic.',
    keys: [
      'i',
      'f',
      'e',
      'l',
      's',
      '(',
      ')',
      '{',
      '}',
      '>',
      '=',
      'p',
      'r',
      'n',
      't',
      '"',
      'g',
      'a',
      'h',
      'o',
    ],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 38,
    minAccuracy: 96,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [178],
    content:
      'int x = 10;\nif (x > 5) {\n    printf("x is greater than 5");\n} else {\n    printf("x is not greater than 5");\n}',
  },
  {
    level: 180,
    order: 180,
    section: 10,
    title: 'C: Arrays',
    description: 'Practice C array initialization and access.',
    keys: [
      'i',
      'n',
      't',
      '[',
      ']',
      '{',
      '}',
      ',',
      ';',
      '=',
      'c',
      'h',
      'a',
      'r',
      'p',
      'f',
      's',
      '%',
      'd',
      '\\',
      '"',
      'D',
      'e',
    ],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 40,
    minAccuracy: 96,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [179],
    isCheckpoint: true,
    content:
      'int numbers[5] = {1, 2, 3, 4, 5};\nchar name[] = "Dennis";\nprintf("%d\\n", numbers[2]);\nprintf("%s\\n", name);',
  },
  {
    level: 181,
    order: 181,
    section: 10,
    title: 'C: Functions',
    description: 'Practice C function prototypes and definitions.',
    keys: [
      'i',
      'n',
      't',
      'a',
      'd',
      '(',
      ')',
      ';',
      '{',
      '}',
      'r',
      'e',
      'u',
      'm',
      'p',
      'f',
      '%',
      's',
      '\\',
    ],
    difficulty: Difficulty.INTERMEDIATE,
    targetWpm: 42,
    minAccuracy: 96,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [180],
    content:
      'int add(int a, int b);\n\nint main() {\n    int sum = add(5, 3);\n    printf("%d\\n", sum);\n    return 0;\n}\n\nint add(int a, int b) {\n    return a + b;\n}',
  },
  {
    level: 182,
    order: 182,
    section: 10,
    title: 'C: Pointers',
    description: 'Practice pointer declaration and dereferencing.',
    keys: [
      'i',
      'n',
      't',
      'v',
      'a',
      'l',
      '=',
      ';',
      '*',
      'p',
      'r',
      '&',
      'f',
      '(',
      ')',
      '%',
      'd',
      '\\',
    ],
    difficulty: Difficulty.EXPERT,
    targetWpm: 45,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [181],
    content:
      'int val = 10;\nint *ptr = &val;\n\nprintf("Value: %d\\n", *ptr);\n*ptr = 20;\nprintf("New Value: %d\\n", val);',
  },
  {
    level: 183,
    order: 183,
    section: 10,
    title: 'C: Pointers in Functions',
    description: 'Practice passing pointers to functions (pass-by-reference).',
    keys: [
      'v',
      'o',
      'i',
      'd',
      'n',
      'c',
      'r',
      'm',
      '(',
      't',
      '*',
      'p',
      ')',
      '{',
      '}',
      ';',
      'x',
      'a',
      '&',
      'f',
      '%',
      'd',
      '\\',
    ],
    difficulty: Difficulty.EXPERT,
    targetWpm: 48,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [182],
    content:
      'void increment(int *p) {\n    (*p)++;\n}\n\nint main() {\n    int x = 5;\n    increment(&x);\n    printf("%d\\n", x);\n    return 0;\n}',
  },
  {
    level: 184,
    order: 184,
    section: 10,
    title: 'C: Structs',
    description: 'Practice defining a struct.',
    keys: [
      's',
      't',
      'r',
      'u',
      'c',
      'P',
      'o',
      'i',
      'n',
      '{',
      '}',
      ';',
      'd',
      'b',
      'l',
      'e',
      'x',
      'y',
    ],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 46,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [183],
    content: 'struct Point {\n    double x;\n    double y;\n};\n\nstruct Point p1;',
  },
  {
    level: 185,
    order: 185,
    section: 10,
    title: 'C: Structs Initialization',
    description: 'Practice initializing and accessing struct members.',
    keys: [
      's',
      't',
      'r',
      'u',
      'c',
      'P',
      'e',
      'o',
      '{',
      '}',
      ';',
      '.',
      '=',
      'p',
      'f',
      '(',
      ')',
      '%',
      'f',
      'l',
      'a',
      'y',
      '\\',
    ],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 48,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [184],
    isCheckpoint: true,
    content:
      'struct Point {\n    double x, y;\n};\n\nint main() {\n    struct Point p1 = {10.0, 20.0};\n    p1.x = 15.5;\n    printf("x: %lf, y: %lf\\n", p1.x, p1.y);\n    return 0;\n}',
  },
  {
    level: 186,
    order: 186,
    section: 10,
    title: 'C: Structs with Pointers',
    description: 'Practice accessing struct members via a pointer.',
    keys: [
      's',
      't',
      'r',
      'u',
      'c',
      'P',
      'o',
      'i',
      'n',
      '*',
      'p',
      '=',
      '&',
      '1',
      ';',
      '(',
      ')',
      '->',
      'x',
      'y',
      'f',
      '%',
      'l',
      'd',
      '\\',
    ],
    difficulty: Difficulty.EXPERT,
    targetWpm: 50,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [185],
    content:
      'struct Point p1 = {10.0, 20.0};\nstruct Point *p = &p1;\n\n(*p).x = 15.0;\np->y = 25.0;\nprintf("x: %lf\\n", p->x);',
  },
  {
    level: 187,
    order: 187,
    section: 10,
    title: 'C: Malloc',
    description: 'Practice dynamic memory allocation with `malloc`.',
    keys: [
      '#',
      'i',
      'n',
      'c',
      'l',
      'u',
      'd',
      'e',
      '<',
      's',
      't',
      'b',
      'h',
      '>',
      'p',
      'r',
      '*',
      '=',
      '(',
      ')',
      'm',
      'o',
      'z',
      'f',
    ],
    difficulty: Difficulty.EXPERT,
    targetWpm: 50,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [186],
    content:
      '#include <stdlib.h>\n\nint *ptr = (int *)malloc(sizeof(int));\nif (ptr == NULL) {\n    printf("Memory allocation failed\\n");\n    return 1;\n}',
  },
  {
    level: 188,
    order: 188,
    section: 10,
    title: 'C: Free',
    description: 'Practice freeing dynamically allocated memory.',
    keys: [
      '*',
      'p',
      't',
      'r',
      '=',
      '(',
      'i',
      'n',
      ')',
      'm',
      'a',
      'l',
      'o',
      'c',
      's',
      'z',
      'e',
      'f',
      ';',
    ],
    difficulty: Difficulty.EXPERT,
    targetWpm: 48,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [187],
    content:
      'int *ptr = (int *)malloc(sizeof(int));\n*ptr = 100;\nprintf("%d\\n", *ptr);\nfree(ptr);',
  },
  {
    level: 189,
    order: 189,
    section: 10,
    title: 'C: Malloc for Structs',
    description: 'Practice using `malloc` for structs.',
    keys: [
      's',
      't',
      'r',
      'u',
      'c',
      'P',
      'o',
      'i',
      'n',
      '*',
      'p',
      '=',
      '(',
      ')',
      'm',
      'a',
      'l',
      'o',
      'z',
      'f',
      ';',
      '->',
      'x',
      'y',
      'e',
    ],
    difficulty: Difficulty.EXPERT,
    targetWpm: 52,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [188],
    content:
      'struct Point *p = (struct Point *)malloc(sizeof(struct Point));\np->x = 5.0;\np->y = 10.0;\nprintf("%lf\\n", p->x);\nfree(p);',
  },
  {
    level: 190,
    order: 190,
    section: 10,
    title: 'C: Memory Checkpoint',
    description: 'Practice allocating an array with `malloc`.',
    keys: [
      'i',
      'n',
      't',
      '*',
      'a',
      'r',
      '=',
      '(',
      ')',
      'm',
      'l',
      'o',
      'c',
      's',
      'z',
      'e',
      'f',
      ';',
      'f',
      'p',
      'd',
      '\\',
      '0',
    ],
    difficulty: Difficulty.EXPERT,
    targetWpm: 53,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [189],
    isCheckpoint: true,
    content:
      'int *arr = (int *)malloc(5 * sizeof(int));\nfor (int i = 0; i < 5; i++) {\n    arr[i] = i * 2;\n    printf("%d\\n", arr[i]);\n}\nfree(arr);',
  },
  {
    level: 191,
    order: 191,
    section: 10,
    title: 'C: File I/O (Write)',
    description: 'Practice writing to files with `fopen` and `fprintf`.',
    keys: [
      '#',
      'i',
      'n',
      'c',
      'l',
      'u',
      'd',
      'e',
      '<',
      's',
      't',
      'o',
      'h',
      '>',
      'F',
      'I',
      'L',
      'E',
      '*',
      'p',
      '=',
      'f',
      '(',
      '"',
      ')',
      ';',
      'r',
      'H',
      'W',
      'd',
      'l',
      'c',
      '\\',
    ],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 50,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [190],
    content:
      '#include <stdio.h>\n\nFILE *fp = fopen("output.txt", "w");\nif (fp != NULL) {\n    fprintf(fp, "Hello, World!\\n");\n    fclose(fp);\n}',
  },
  {
    level: 192,
    order: 192,
    section: 10,
    title: 'C: File I/O (Read)',
    description: 'Practice reading from files with `fopen` and `fgets`.',
    keys: [
      'F',
      'I',
      'L',
      'E',
      '*',
      'p',
      '=',
      'f',
      'o',
      '(',
      '"',
      ')',
      ';',
      'c',
      'h',
      'a',
      'r',
      'b',
      'u',
      '[',
      ']',
      'w',
      'g',
      's',
      't',
      'd',
      '\\',
    ],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 52,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [191],
    content:
      'FILE *fp = fopen("input.txt", "r");\nchar buffer[100];\nif (fp != NULL) {\n    while (fgets(buffer, 100, fp) != NULL) {\n        printf("%s", buffer);\n    }\n    fclose(fp);\n}',
  },
  {
    level: 193,
    order: 193,
    section: 10,
    title: 'C: String Header (strcpy)',
    description: 'Practice using `strcpy` from `<string.h>`.',
    keys: [
      '#',
      'i',
      'n',
      'c',
      'l',
      'u',
      'd',
      'e',
      '<',
      's',
      't',
      'r',
      'g',
      'h',
      '>',
      'c',
      'a',
      'o',
      'p',
      'y',
      '(',
      ')',
      ';',
      '"',
      'H',
      'l',
      'W',
      'f',
      'd',
      '\\',
    ],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 48,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [192],
    content:
      '#include <string.h>\n\nchar src[] = "Hello, World!";\nchar dest[20];\nstrcpy(dest, src);\nprintf("%s\\n", dest);',
  },
  {
    level: 194,
    order: 194,
    section: 10,
    title: 'C: String Header (strlen)',
    description: 'Practice using `strlen` from `<string.h>`.',
    keys: [
      '#',
      'i',
      'n',
      'c',
      'l',
      'u',
      'd',
      'e',
      '<',
      's',
      't',
      'r',
      'g',
      'h',
      '>',
      'c',
      'a',
      'm',
      'y',
      '(',
      ')',
      ';',
      '"',
      'T',
      'p',
      'z',
      'e',
      'f',
      '%',
      'l',
      'd',
      '\\',
    ],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 47,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [193],
    content:
      '#include <string.h>\n\nchar myStr[] = "Test String";\nsize_t len = strlen(myStr);\nprintf("Length: %zu\\n", len);',
  },
  {
    level: 195,
    order: 195,
    section: 10,
    title: 'C: String Header Checkpoint',
    description: 'Practice using `strcat` from `<string.h>`.',
    keys: [
      '#',
      'i',
      'n',
      'c',
      'l',
      'u',
      'd',
      'e',
      '<',
      's',
      't',
      'r',
      'g',
      'h',
      '>',
      'c',
      'a',
      '1',
      '2',
      '(',
      ')',
      ';',
      '"',
      'H',
      'o',
      'W',
      'l',
      'd',
      '!',
      'f',
      '%',
      'p',
      '\\',
    ],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 50,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [194],
    isCheckpoint: true,
    content:
      '#include <string.h>\n\nchar str1[50] = "Hello, ";\nchar str2[] = "World!";\nstrcat(str1, str2);\nprintf("%s\\n", str1);',
  },
  {
    level: 196,
    order: 196,
    section: 10,
    title: 'C: Header Files (Creation)',
    description: 'Practice creating a simple header file guard.',
    keys: [
      '#',
      'i',
      'f',
      'n',
      'd',
      'e',
      'M',
      'Y',
      '_',
      'H',
      'A',
      'R',
      'F',
      'T',
      'G',
      '(',
      ')',
      ';',
      'O',
    ],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 45,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [195],
    content:
      '#ifndef MY_HEADER_H\n#define MY_HEADER_H\n\nint add(int a, int b);\n\n#endif // MY_HEADER_H',
  },
  {
    level: 197,
    order: 197,
    section: 10,
    title: 'C: Header Files (Implementation)',
    description: 'Practice implementing a header file function.',
    keys: [
      '#',
      'i',
      'n',
      'c',
      'l',
      'u',
      'd',
      'e',
      '"',
      'm',
      'y',
      'h',
      'a',
      'r',
      '.',
      '>',
      't',
      '(',
      ')',
      '{',
      '}',
      'b',
      'o',
      'f',
    ],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 46,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [196],
    content: '#include "my_header.h"\n\nint add(int a, int b) {\n    return a + b;\n}',
  },
  {
    level: 198,
    order: 198,
    section: 10,
    title: 'C: Header Files (Usage)',
    description: 'Practice using a custom header file.',
    keys: [
      '#',
      'i',
      'n',
      'c',
      'l',
      'u',
      'd',
      'e',
      '<',
      's',
      't',
      'o',
      'h',
      '>',
      '"',
      'm',
      'y',
      'a',
      'r',
      '.',
      'p',
      'f',
      '(',
      ')',
      '0',
      'g',
      'd',
      '\\',
    ],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 48,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [197],
    content:
      '#include <stdio.h>\n#include "my_header.h"\n\nint main() {\n    int sum = add(10, 20);\n    printf("Sum: %d\\n", sum);\n    return 0;\n}',
  },
  {
    level: 199,
    order: 199,
    section: 10,
    title: 'C: Typedef',
    description: 'Practice using `typedef` for structs.',
    keys: [
      't',
      'y',
      'p',
      'e',
      'd',
      'f',
      's',
      'r',
      'u',
      'c',
      '{',
      '}',
      'P',
      'o',
      'i',
      'n',
      ';',
      'x',
      'm',
      'a',
      '.',
      '=',
      'l',
      'g',
      'b',
    ],
    difficulty: Difficulty.ADVANCED,
    targetWpm: 50,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [198],
    content:
      'typedef struct {\n    double x;\n    double y;\n} Point;\n\nint main() {\n    Point p1;\n    p1.x = 1.0;\n    p1.y = 2.0;\n    return 0;\n}',
  },
  {
    level: 200,
    order: 200,
    section: 10,
    title: 'C: Final Checkpoint',
    description: 'Practice structs and pointers.',
    keys: [
      's',
      't',
      'r',
      'u',
      'c',
      'P',
      'e',
      'o',
      'n',
      '{',
      '}',
      ';',
      'h',
      'a',
      '*',
      'm',
      'g',
      'v',
      'i',
      'd',
      'p',
      'f',
      '(',
      ')',
      '->',
      'l',
      '\\',
      '%',
    ],
    difficulty: Difficulty.EXPERT,
    targetWpm: 55,
    minAccuracy: 97,
    exerciseType: ExerciseType.CODE,
    targetFingers: [],
    unlockAfter: [199],
    isCheckpoint: true,
    content:
      'struct Person {\n    char *name;\n    int age;\n};\n\nvoid printPerson(struct Person *p) {\n    printf("Name: %s\\n", p->name);\n    printf("Age: %d\\n", p->age);\n}',
  },
];
