/* eslint-disable no-console */

// ============================================================================
// SECTION 7: PYTHON CODING (Levels 101-130) — 30 lessons
// ============================================================================
const pythonContents = [
  'print("Hello, World!")',
  'name = input("Enter your name: ")',
  'for i in range(5):\n    print(f"Step {i}: processing")',
  'def greet(name: str) -> str:\n    return f"Hi, {name}!"',
  'scores = [88, 92, 79, 95]\ntotal = sum(scores)\naverage = total / len(scores)',
  'with open("notes.txt", "r") as f:\n    lines = [line.strip() for line in f if line.strip()]',
  'try:\n    value = int(user_input)\nexcept ValueError:\n    print("Invalid number")',
  'import math\nprint(f"sqrt(81) = {math.sqrt(81):.1f}")\nprint(f"pow(2,10) = {math.pow(2, 10):.0f}")',
  'class Dog:\n    def __init__(self, name: str, breed: str):\n        self.name = name\n        self.breed = breed\n    def bark(self):\n        return f"{self.name}: woof!"',
  'evens = [x * 2 for x in range(10) if x % 2 == 0]\nprint(evens)',
  'import json\npayload = json.dumps({"user": "ada", "level": 7}, indent=2)\nprint(payload)',
  'from datetime import datetime\nnow = datetime.now()\nprint(now.strftime("%Y-%m-%d %H:%M:%S"))',
  'import re\ntext = "order123 batch456"\nmatches = re.findall(r"[a-z]+\\d+", text)\nprint(matches)',
  'import numpy as np\narr = np.array([2, 4, 6, 8])\nprint(f"mean={arr.mean():.1f}")',
  'import pandas as pd\ndf = pd.DataFrame({"score": [88, 92, 79]})\nprint(df.describe().to_string())',
  'import asyncio\nasync def fetch(url: str):\n    await asyncio.sleep(0.2)\n    return f"fetched {url}"',
  'square = lambda x: x ** 2\nresult = square(12)\nprint(result)',
  'unique = {1, 2, 2, 3, 5}\nprint(f"unique count: {len(unique)}")\nprint(sorted(unique))',
  'words = ["hello", "world", "typing"]\nupper = list(map(str.upper, words))\nprint(upper)',
  'items = ["alpha", "beta", "gamma"]\nfor idx, val in enumerate(items, start=1):\n    print(f"{idx}. {val}")',
  'config = {"host": "localhost", "port": 8000}\nextra = {"debug": True, "retries": 3}\nmerged = {**config, **extra}',
  'value = 255\nprint(f"hex={hex(value)} bin={bin(value)} oct={oct(value)}")',
  'status = "active" if len(scores) > 3 else "idle"\nprint(status.upper())',
  'names = ["Zoe", "Ada", "Mia", "Leo"]\nprint(sorted(names))\nprint(sorted(names, reverse=True))',
  'from collections import Counter\ntext = "abracadabra"\ncounts = Counter(text)\nprint(counts.most_common(3))',
  'from pathlib import Path\npath = Path("data/results.csv")\nprint(path.exists())\nprint(path.name)',
  'def fibonacci(n: int):\n    a, b = 0, 1\n    for _ in range(n):\n        yield a\n        a, b = b, a + b\nprint(list(fibonacci(6)))',
  'user = {"id": 42, "name": "Ada", "role": "admin"}\nif user.get("role") == "admin":\n    print("welcome admin")',
  'data = {"alice": 88, "bob": 92}\ntotal = sum(data.values())\navg = total / len(data)\nprint(f"{total} {avg:.1f}")',
  'numbers = [3, 1, 4, 1, 5, 9]\nnumbers.sort(reverse=True)\nprint(numbers[:3])',
];

// ============================================================================
// SECTION 8: JAVA CODING (Levels 131-160) — 30 lessons
// ============================================================================
const javaContents = [
  'public class Main { public static void main(String[] args) { System.out.println("Hello, World!"); } }',
  'int activeUsers = 42;\ndouble ratio = activeUsers / 100.0;\nSystem.out.printf("ratio=%.2f%n", ratio);',
  'String greeting = String.format("Hello, %s!", "Ada");\nSystem.out.println(greeting);',
  'for (int i = 0; i < 5; i++) { System.out.printf("index=%d%n", i); }',
  'int[] scores = {88, 92, 79};\nint total = java.util.Arrays.stream(scores).sum();\nSystem.out.println(total);',
  'try (java.io.BufferedReader br = new java.io.BufferedReader(new java.io.FileReader("input.txt"))) { String line = br.readLine(); System.out.println(line); } catch (java.io.IOException e) { e.printStackTrace(); }',
  'double root = Math.sqrt(81);\ndouble power = Math.pow(2, 10);\nSystem.out.println(root + " " + power);',
  'class Dog { private final String name; private final String breed; public Dog(String n, String b) { name = n; breed = b; } public String bark() { return name + ": woof!"; } }',
  'java.util.List<Integer> evens = new java.util.ArrayList<>();\nfor (int i = 0; i < 10; i++) if (i % 2 == 0) evens.add(i * 2);\nSystem.out.println(evens);',
  'java.util.Map<String, Integer> inventory = new java.util.HashMap<>();\ninventory.put("apples", 12);\ninventory.merge("apples", 3, Integer::sum);',
  'java.time.LocalDate today = java.time.LocalDate.now();\nString iso = today.format(java.time.format.DateTimeFormatter.ISO_DATE);\nSystem.out.println(iso);',
  'java.util.regex.Pattern pat = java.util.regex.Pattern.compile("[a-z]+\\\\d+");\njava.util.regex.Matcher m = pat.matcher("order123");\nSystem.out.println(m.find());',
  'record Point(int x, int y) {}\nPoint p = new Point(3, 4);\ndouble dist = Math.hypot(p.x(), p.y());',
  'void log(String msg) { System.out.println("[LOG] " + msg + " at " + java.time.Instant.now()); }',
  'java.util.List<String> names = java.util.List.of("Ada", "Bob", "Mia");\nnames.stream().filter(s -> s.length() > 2).forEach(System.out::println);',
  'String csv = String.join(";", java.util.List.of("id", "name", "score"));\nSystem.out.println(csv);',
  'int hex = Integer.parseInt("FF", 16);\nString hexStr = Integer.toHexString(255);\nSystem.out.println(hex + " " + hexStr);',
  'int binary = Integer.parseInt("101010", 2);\nString binStr = Integer.toBinaryString(42);\nSystem.out.println(binary + " " + binStr);',
  'int octal = Integer.parseInt("77", 8);\nString octStr = Integer.toOctalString(64);\nSystem.out.println(octal + " " + octStr);',
  'boolean isNumeric = "90210".matches("\\\\d+");\nboolean hasAt = "ada@test.com".contains("@");\nSystem.out.println(isNumeric && hasAt);',
  'java.util.stream.IntStream.rangeClosed(1, 5).map(i -> i * i).forEach(System.out::println);',
  'java.util.List<String> upper = java.util.stream.Stream.of("alpha", "beta", "gamma").map(String::toUpperCase).toList();\nSystem.out.println(upper);',
  'java.util.Optional<String> opt = java.util.Optional.ofNullable(getUsername());\nString user = opt.orElse("guest");\nSystem.out.println(user);',
  'java.time.Duration uptime = java.time.Duration.between(startTime, java.time.Instant.now());\nlong secs = uptime.toSeconds();\nSystem.out.println(secs);',
  'java.time.LocalDateTime now = java.time.LocalDateTime.now();\nString fmt = now.format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm"));\nSystem.out.println(fmt);',
  'enum Status { ACTIVE, IDLE, OFFLINE }\nStatus s = Status.ACTIVE;\nSystem.out.println(s.name());',
  'java.util.concurrent.CompletableFuture<String> future = java.util.concurrent.CompletableFuture.supplyAsync(() -> "hello").thenApply(String::toUpperCase);\nSystem.out.println(future.join());',
  'var grouped = java.util.stream.Stream.of("apple", "apricot", "banana").collect(java.util.stream.Collectors.groupingBy(s -> s.charAt(0)));\nSystem.out.println(grouped);',
  'sealed interface Shape permits Circle, Rectangle {}\nrecord Circle(double r) implements Shape {}\nrecord Rectangle(double w, double h) implements Shape {}',
  'java.net.http.HttpRequest req = java.net.http.HttpRequest.newBuilder().uri(java.net.URI.create("https://api.example.com/users")).GET().build();\nSystem.out.println(req.uri());',
];

// ============================================================================
// SECTION 9: C++ CODING (Levels 161-190) — 30 lessons
// ============================================================================
const cppContents = [
  '#include <iostream>\nint main() { std::cout << "Hello, World!" << std::endl; return 0; }',
  'int active_users = 42;\ndouble ratio = active_users / 100.0;\nstd::cout << ratio << std::endl;',
  'std::string greeting = std::string("Hello, ") + "Ada" + "!";\nstd::cout << greeting << std::endl;',
  'for (int i = 0; i < 5; ++i) { std::cout << "i=" << i << "\\n"; }',
  'std::vector<int> scores = {88, 92, 79};\nint sum = std::accumulate(scores.begin(), scores.end(), 0);\nstd::cout << sum << std::endl;',
  'std::ifstream in("input.txt");\nstd::string line;\nwhile (std::getline(in, line)) { std::cout << line << "\\n"; }',
  'int divisor = 0;\ntry { if (divisor == 0) throw std::runtime_error("zero"); int x = 10 / divisor; } catch (const std::exception& e) { std::cerr << e.what() << "\\n"; }',
  '#include <cmath>\ndouble root = std::sqrt(81.0);\ndouble pw = std::pow(2.0, 10);\nstd::cout << root << " " << pw << "\\n";',
  'class Dog { std::string name, breed; public: Dog(std::string n, std::string b) : name(n), breed(b) {} std::string bark() const { return name + ": woof!"; } };',
  'std::vector<int> evens;\nfor (int i = 0; i < 10; ++i) if (i % 2 == 0) evens.push_back(i * 2);',
  '#include <unordered_map>\nstd::unordered_map<std::string,int> inv;\ninv["apples"] = 12;\ninv["oranges"] = 7;\nstd::cout << inv["apples"] << "\\n";',
  '#include <chrono>\nauto now = std::chrono::system_clock::now();\nauto t = std::chrono::system_clock::to_time_t(now);\nstd::cout << std::ctime(&t);',
  '#include <regex>\nstd::regex pat(R"([a-z]+\\d+)");\nbool ok = std::regex_search("order123", pat);\nstd::cout << ok << "\\n";',
  'std::array<int,4> arr = {1, 2, 3, 4};\ndouble mean = std::accumulate(arr.begin(), arr.end(), 0.0) / arr.size();\nstd::cout << mean << "\\n";',
  'std::ofstream out("output.txt");\nout << "name,Ada\\nscore,88\\n";',
  'auto square = [](int x) { return x * x; };\nstd::cout << square(12) << "\\n";',
  'std::set<int> uniq = {1, 2, 3, 5};\nstd::cout << uniq.size() << "\\n";',
  'std::map<int,std::string> id2name = {{1, "Ada"}, {2, "Mia"}};\nstd::cout << id2name[1] << "\\n";',
  '#include <algorithm>\nstd::string s = "42";\nint v = std::stoi(s);\nstd::string back = std::to_string(v);\nstd::cout << back << "\\n";',
  'std::vector<std::string> words = {"alpha", "beta"};\nstd::string csv;\nfor (auto &w : words) csv += (csv.empty() ? "" : ";") + w;\nstd::cout << csv << "\\n";',
  'int val = 255;\nstd::cout << std::hex << val << " " << std::dec << val << "\\n";',
  'std::bitset<8> bits(42);\nstd::cout << bits.to_string() << "\\n";',
  'int octVal = 64;\nstd::cout << std::oct << octVal << std::dec << "\\n";',
  'std::string code = "90210";\nbool numeric = std::all_of(code.begin(), code.end(), ::isdigit);\nstd::cout << numeric << "\\n";',
  'std::vector<int> v = {3, 1, 4, 5};\nstd::sort(v.begin(), v.end(), std::greater<int>());\nfor (int x : v) std::cout << x << " ";',
  '#include <numeric>\nstd::vector<int> nums(5);\nstd::iota(nums.begin(), nums.end(), 1);\nint prod = std::accumulate(nums.begin(), nums.end(), 1, std::multiplies<int>());',
  'std::vector<int> data = {3, 1, 4, 5};\nauto [minIt, maxIt] = std::minmax_element(data.begin(), data.end());\nstd::cout << *minIt << " " << *maxIt << "\\n";',
  '#include <optional>\nstd::optional<std::string> opt;\nstd::string user = opt.value_or("guest");\nstd::cout << user << "\\n";',
  '#include <filesystem>\nnamespace fs = std::filesystem;\nbool exists = fs::exists("data/output.csv");\nstd::cout << exists << "\\n";',
  'struct Point { int x, y; };\nPoint p{3, 4};\ndouble d = std::hypot(p.x, p.y);\nstd::cout << d << "\\n";',
];

// ============================================================================
// SECTION 10: C CODING (Levels 191-220) — 30 lessons
// ============================================================================
const cContents = [
  '#include <stdio.h>\nint main() { printf("Hello, World!\\n"); return 0; }',
  'int active_users = 42;\ndouble ratio = active_users / 100.0;\nprintf("ratio=%.2f\\n", ratio);',
  'char greeting[32];\nsnprintf(greeting, sizeof(greeting), "Hello, %s!", "Ada");\nputs(greeting);',
  'for (int i = 0; i < 5; i++) { printf("i=%d\\n", i); }',
  'int scores[] = {88, 92, 79};\nint total = 0;\nfor (int i = 0; i < 3; i++) total += scores[i];\nprintf("%d\\n", total);',
  'FILE *fp = fopen("input.txt", "r");\nif (fp) { char buf[256]; while (fgets(buf, sizeof(buf), fp)) printf("%s", buf); fclose(fp); }',
  'double safe_divide(double a, double b) { if (b == 0) { fprintf(stderr, "divide by zero\\n"); return 0; } return a / b; }',
  '#include <math.h>\ndouble root = sqrt(81.0);\ndouble pw = pow(2.0, 10);\nprintf("%.1f %.1f\\n", root, pw);',
  'struct Dog { char name[32]; char breed[32]; };\nstruct Dog d = {"Rex", "Labrador"};\nprintf("%s: woof!\\n", d.name);',
  'int evens[5]; int idx = 0;\nfor (int i = 0; i < 10; i++) if (i % 2 == 0) evens[idx++] = i * 2;',
  '#include <string.h>\nchar key[16] = "apples";\nint val = 12;\nprintf("%s=%d\\n", key, val);',
  '#include <time.h>\ntime_t now = time(NULL);\nstruct tm *tm = localtime(&now);\nprintf("%04d-%02d-%02d\\n", tm->tm_year + 1900, tm->tm_mon + 1, tm->tm_mday);',
  '#include <regex.h>\nregex_t re;\nregcomp(&re, "[a-z]+[0-9]+", REG_EXTENDED);\nint ok = regexec(&re, "order123", 0, NULL, 0);\nregfree(&re);',
  'int arr[] = {1, 2, 3, 4};\nint n = 4; double mean = 0;\nfor (int i = 0; i < n; i++) mean += arr[i];\nmean /= n;\nprintf("%.1f\\n", mean);',
  'FILE *out = fopen("output.txt", "w");\nif (out) { fprintf(out, "name,Ada\\nscore,88\\n"); fclose(out); }',
  'int square(int x) { return x * x; }\nprintf("%d\\n", square(12));',
  'int a[] = {1, 2, 3, 5};\nint n2 = 4; int uniq = 1;\nfor (int i = 1; i < n2; i++) if (a[i] != a[i-1]) uniq++;\nprintf("%d\\n", uniq);',
  'struct Entry { int id; char name[16]; };\nstruct Entry e = {1, "Ada"};\nprintf("%d %s\\n", e.id, e.name);',
  'char numStr[16] = "42";\nint v = atoi(numStr);\nchar back[16]; snprintf(back, sizeof(back), "%d", v);',
  'char words[2][8] = {"alpha", "beta"};\nchar csv[32] = "";\nfor (int i = 0; i < 2; i++) { if (i) strcat(csv, ";"); strcat(csv, words[i]); }',
  'int val = 255;\nprintf("hex=%x dec=%d\\n", val, val);',
  'unsigned bits = 42;\nfor (int i = 7; i >= 0; i--) putchar((bits >> i) & 1 ? \'1\' : \'0\');\nputchar(\'\\n\');',
  'int octVal = 64;\nprintf("oct=%o\\n", octVal);',
  '#include <ctype.h>\nchar code[] = "90210";\nint all_digit = 1;\nfor (int i = 0; code[i]; i++) if (!isdigit((unsigned char)code[i])) all_digit = 0;',
  'int cmp_int(const void *a, const void *b) { return *(int*)a - *(int*)b; }\nint v2[] = {3, 1, 4, 5};\nqsort(v2, 4, sizeof(int), cmp_int);',
  'int nums[5];\nfor (int i = 0; i < 5; i++) nums[i] = i + 1;\nint prod = 1;\nfor (int i = 0; i < 5; i++) prod *= nums[i];',
  'int data[] = {3, 1, 4, 5};\nint mn = data[0], mx = data[0];\nfor (int i = 1; i < 4; i++) { if (data[i] < mn) mn = data[i]; if (data[i] > mx) mx = data[i]; }',
  'char *opt = NULL;\nchar *user = opt ? opt : "guest";\nprintf("%s\\n", user);',
  '#include <sys/stat.h>\nstruct stat st;\nint exists = (stat("data/output.csv", &st) == 0);\nprintf("%d\\n", exists);',
  'struct Point { int x; int y; };\nstruct Point p = {3, 4};\ndouble d = hypot(p.x, p.y);\nprintf("%.1f\\n", d);',
];

// Export raw arrays for use in seed.ts with makeLessons
export { pythonContents, javaContents, cppContents, cContents };
